RMS-52932 Front.API: Документировать метод ShowExtendedKeyboardDialog
iiko/front.api.doc pull request #101
Opened 2021-12-09 01:36 UTC by zed220

2021-12-10 15:56 UTC, rgalk requested changes

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +Далее в статье будем использовать именно этот подход - показ окна ввода строки при нажатии на кнопку.
```suggestion
Далее в статье будем использовать именно этот подход — показ окна ввода строки при нажатии на кнопку.
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +Строка, которая уже будет задана при показе диалога.
```suggestion
Строка, которая будет задана при показе диалога.
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +Строка, которая уже будет задана при показе диалога.
Не нравится мне эта строка, как-то по-другому нужно написать.

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +- `bool capitalize`- необязательный параметр.
```suggestion
- `bool capitalize` - необязательный параметр.
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +Писать ли слова автоматически с заглавной буквы.
Каждое слово с заглавной буквы?

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +Игнорируется при выставленном свойстве `isPassword = true`.
```suggestion
Игнорируется, если свойство `isPassword` равно `true`.
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +При выставлении в `true` свойства `isMultiline` и `capitalize` игнорируются.
```suggestion
Игнорируется, если свойства `isMultiline` и `capitalize` равны `true`. 
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +- `bool enableCardSlider`- необязательный параметр.
```suggestion
- `bool enableCardSlider` - необязательный параметр.
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +- `bool enableBarcode`- необязательный параметр.
```suggestion
- `bool enableBarcode` - необязательный параметр.
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +- `bool isPassword`- необязательный параметр.
```suggestion
- `bool isPassword` - необязательный параметр.
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +    if(strResult == null)
```suggestion
    if (strResult == null)
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +    if(strResult == null)
```suggestion
    if (strResult == null)
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +Результрат необходимо привести к типу [`CardInputDialogResult`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_View_CardInputDialogResult.htm):
```suggestion
Результат необходимо привести к типу [`CardInputDialogResult`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_View_CardInputDialogResult.htm):
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +    if(cardResult == null)
```suggestion
    if (cardResult == null)
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +Результрат необходимо привести к типу [`BarcodeInputDialogResult`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_View_BarcodeInputDialogResult.htm):
```suggestion
Результат необходимо привести к типу [`BarcodeInputDialogResult`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_View_BarcodeInputDialogResult.htm):
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +    if(barcodeResult == null)
```suggestion
    if (barcodeResult == null)
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +При этом, параметры `enableCardSlider` и `enableBarcode` продолжают работать.
```suggestion
 Однако, остается возможность передать `true` в параметры `enableCardSlider` и `enableBarcode`,  что позволит  прокатывать карту и сканировать штрих-код .
```

2021-12-10 15:56 UTC, rgalk commented on v7/ru/ExtendedKeyboardDialog.md
> +При этом, сканирование сервисных штрихкодов не будет учитываться.
```suggestion
При этом сканирование сервисных штрихкодов не будет учитываться.
```

2021-12-20 08:06 UTC, zed220 commented on v7/ru/ExtendedKeyboardDialog.md
> +Писать ли слова автоматически с заглавной буквы.
Да. Многие (если не все) разделители приводят к заглавной букве - (. , ; ` ")

2021-12-20 08:51 UTC, rgalk approved these changes

2021-12-20 08:51 UTC, merged