RMS-53092 Front API: Выпилить GetModifierAmountString из IOperationSe…
iiko/front.api.doc pull request #102
Opened 2021-12-21 08:55 UTC by OlgaBelilovskaya

…rvice в API V7.

2021-12-23 08:37 UTC, zed220 commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +	// Настройка способа отображения количества групповых модификаторов блюда.
Отступы скачат

2021-12-23 08:40 UTC, zed220 commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +    var multiplyAmountString = $"\u00D7{modifierAmount.ToString(culture)}";
\u00D7 - можно сделать локальную константу, т.к. не все помнят коды юникода наизусть, как-то как:
const char multSign = "\u00D7"

2021-12-23 08:41 UTC, zed220 commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +	// Относительное количество модификатора.
Тоже отступ странный

2021-12-23 08:43 UTC, zed220 commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +    var amount = modifierAmount - defaultAmount;
Поскольку метод публичный, я думаю, надо постараться названия поточнее сделать. Может, deltaAmount или ещё как-нибудь?

2021-12-23 08:45 UTC, zed220 commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +            var amountFormatted= $"{amount:+#;-#;0}";
пробел перед равно пропал

2021-12-23 08:51 UTC, zed220 commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +            return amountFormatted.ToString(culture);
А это работает? Мы уже строкой выше применили интерполяцию, которая вроде берёт по умолчанию CurrentCulture. Выглядит так, что тут нельзя использовать интерполяцию.

2021-12-23 10:04 UTC, rgalk commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +    var showDeltaAmount = ServiceFactory.Instance.Config.CafeSetup.Instance.DisplayRelativeNumberOfModifiers;
Эту настройку предлагаю запихать в аргументы метода. У внешних разработчиков же нет доступа к этому свойству.
Либо показать через `PluginContext.Operations.GetHostRestaurant().DisplayRelativeNumberOfModifiers`.

2021-12-23 10:56 UTC, zed220 commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +public static string CalculateModifierAmountString(decimal modifierAmount, int defaultAmount, bool hideIfDefaultAmount, bool isPaid, bool isAmountIndependentOfParentAmount)
Вообще как новость статья выглядит слишком большой. Я бы всё, что начинается со слова "Например", выделил в отдельную статью. Для новости хватит первого абзаца, может ещё пару слов.

2021-12-23 10:58 UTC, zed220 requested changes
Думаю, надо разделить на новость и статью.

2022-01-19 09:02 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +	// Настройка способа отображения количества групповых модификаторов блюда.
исправила

2022-01-19 09:02 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +    var multiplyAmountString = $"\u00D7{modifierAmount.ToString(culture)}";
исправила

2022-01-19 09:02 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +	// Относительное количество модификатора.
исправила

2022-01-19 09:02 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +    var amount = modifierAmount - defaultAmount;
сделала deltaAmount

2022-01-19 09:02 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +            var amountFormatted= $"{amount:+#;-#;0}";
исправила

2022-01-19 09:03 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +            return amountFormatted.ToString(culture);
да, убрала culture. интерполяцию оставила, без нее не. Проверила. Оставляю?

2022-01-19 09:04 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +    var showDeltaAmount = ServiceFactory.Instance.Config.CafeSetup.Instance.DisplayRelativeNumberOfModifiers;
Да, не подумала. Сделала DisplayRelativeNumberOfModifiers.

2022-01-19 09:04 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +public static string CalculateModifierAmountString(decimal modifierAmount, int defaultAmount, bool hideIfDefaultAmount, bool isPaid, bool isAmountIndependentOfParentAmount)
разделила на новость и статью.

2022-01-19 09:06 UTC, OlgaBelilovskaya commented
Вроде все поправила.

2022-01-19 10:40 UTC, zed220 commented on v7/ru/DisplayRelativeNumberOfModifiers.md
> +    // Если стоит галка "Количество не зависит от количества блюда", то всегда пишем "+N".
```suggestion
    // Если опция "Количество не зависит от количества блюда" включена, то всегда пишем "+N".
```

2022-01-19 10:40 UTC, zed220 commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
>  В API V7 для ресторана появилась возможность настроить способ отображения количества групповых модификаторов блюда.
Возможно, стоит подвинуть новость на дату поближе к текущей?

2022-01-20 08:25 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
>  В API V7 для ресторана появилась возможность настроить способ отображения количества групповых модификаторов блюда.
Поправила на 17е. Я вот тоже думала, а потом подумала мол мы настройку то давно добавили.. )))

2022-01-20 08:25 UTC, OlgaBelilovskaya commented on v7/ru/DisplayRelativeNumberOfModifiers.md
> +    // Если стоит галка "Количество не зависит от количества блюда", то всегда пишем "+N".
Поправила. Меня тоже бесило это, но решила что зато понятнее хаха.

2022-01-20 09:30 UTC, zed220 approved these changes

2022-02-03 19:46 UTC, merged