RMS-53338: Предотвращение удаления внешнего типа оплаты из заказа по …
iiko/front.api.doc pull request #108
Opened 2022-05-18 22:47 UTC by nick-samygin

…инициативе плагина

Добавлена новость

2022-05-18 23:33 UTC, vcpp requested changes

2022-05-18 23:33 UTC, vcpp commented on _posts/2022-03-18-external-payment-removing-api-notification.md
> +title: В API V8 добавлен механизм предотвращения удаления внешнего типа оплаты из заказа по инициативе плагина
Неоднозначно написано. Можно подумать, что плагин инициирует удаление, а механизм это удаление предотвращает.

2022-05-18 23:33 UTC, vcpp commented on _posts/2022-03-18-external-payment-removing-api-notification.md
> +В интерфейс [`IPaymentProcessor`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_IPaymentProcessor.htm) добавлен метод [`OnPaymentDeleting`](https://iiko.github.io/front.api.sdk/v8/ht
Вместо _страницы_ мы используем термин _экран_.
Кроме того, скобки я бы убрал, это важная часть предложения, а не пояснение.

2022-05-18 23:33 UTC, vcpp commented on _posts/2022-03-18-external-payment-removing-api-notification.md
> +В интерфейс [`IPaymentProcessor`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_IPaymentProcessor.htm) добавлен метод [`OnPaymentDeleting`](https://iiko.github.io/front.api.sdk/v8/ht
_уведомляющий об удалении_ — можно подумать, что удаление свершилось, и вот уведомление об этом.
Я бы сформулировал так:
```suggestion
При попытке удаления внешней оплаты вызовется метод [`OnPaymentDeleting`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_IPaymentProcessor_OnPaymentDeleting.htm) у соответствующего [`IPaymentProcessor`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_IPaymentProcessor.htm). 
```

Можно добавить, что пока это работает только на экране оплаты. Я так понимаю, в полном варианте данный метод должен также вызываться и при удалении оплаты другим плагином через `DeleteExternalPaymentItem`.

2022-05-18 23:33 UTC, vcpp commented on _posts/2022-03-18-external-payment-removing-api-notification.md
> +Отменить удаление можно двумя способами: выкинув исключение [`PaymentActionCancelledException`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Exceptions_PaymentActionCancelledExcepti
Плагин ведь не обязан отменять удаление. Давай расширим описание, сказав, что плагин может либо корректно обработать удаление оплаты, либо запретить удаление. Дальше уже два способа запретить — тихая отмена и сообщение об ошибке.

Ну и очепятки надо причесать, а то запятые, «никакого сообщени**е**»...

2022-05-18 23:33 UTC, vcpp commented on _posts/2022-03-18-external-payment-removing-api-notification.md
> +Ранее была возможна ситуация, когда при наличии внешнего типа оплаты в заказе его можно было удалить в моменте обработки платежной системой. Из-за чего платеж никогда не был сторнирован на стороне вн
Давай аккуратнее с терминологией. Тип оплаты — это PaymentType. На фронте тип оплаты удалить нельзя, это серверный справочник. PaymentItem — это оплата, ExternalPaymentItem — оплата внешним типом оплаты или просто внешняя оплата.

Что такое «удалить в моменте обработки платежной системой»?

«... Из-за чего» — это не выглядит как новое предложение.

И, как я уже отметил, упускается возможность корректно сторнировать оплату при удалении, фокус почему-то именно на запрете удаления.

2022-05-19 20:27 UTC, nick-samygin commented on _posts/2022-03-18-external-payment-removing-api-notification.md
> +title: В API V8 добавлен механизм предотвращения удаления внешнего типа оплаты из заказа по инициативе плагина
Изменил описание

2022-05-19 20:27 UTC, nick-samygin commented on _posts/2022-03-18-external-payment-removing-api-notification.md
> +В интерфейс [`IPaymentProcessor`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_IPaymentProcessor.htm) добавлен метод [`OnPaymentDeleting`](https://iiko.github.io/front.api.sdk/v8/ht
Изменил описание

2022-05-19 20:28 UTC, nick-samygin commented on _posts/2022-03-18-external-payment-removing-api-notification.md
> +В интерфейс [`IPaymentProcessor`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_IPaymentProcessor.htm) добавлен метод [`OnPaymentDeleting`](https://iiko.github.io/front.api.sdk/v8/ht
Использую твою формулировку

2022-05-19 20:31 UTC, nick-samygin commented on _posts/2022-03-18-external-payment-removing-api-notification.md
> +Отменить удаление можно двумя способами: выкинув исключение [`PaymentActionCancelledException`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Exceptions_PaymentActionCancelledExcepti
Поправил орфографию и опечатку

2022-05-19 20:32 UTC, nick-samygin commented on _posts/2022-03-18-external-payment-removing-api-notification.md
> +Ранее была возможна ситуация, когда при наличии внешнего типа оплаты в заказе его можно было удалить в моменте обработки платежной системой. Из-за чего платеж никогда не был сторнирован на стороне вн
Полностью переписал этот фрагмент

2022-05-19 20:37 UTC, nick-samygin commented
Поправил все замечания

2022-05-24 23:18 UTC, merged