RMS-53692 Добавить в документацию по АПИ инфо о поездке и связанных с…
iiko/front.api.doc pull request #112
Opened 2022-08-16 17:46 UTC by OlgaBelilovskaya

… поездкой методах.

2022-08-17 21:50 UTC, zed220 commented
Лучше каждое предложение делать на новой строке. Так ревьювить проще.

2022-08-17 21:56 UTC, zed220 requested changes

2022-08-17 21:56 UTC, zed220 commented on _posts/2022-08-16-ride.md
> +Поездка нужна для работы со внешними курьерскими службами (сейчас это Яндекс-Доставка) для отслеживания пути доставочного заказа от начального статуса поиска внешнего курьера до финального статуса до
```suggestion
Поездка используется при работе с внешними курьерскими службами (сейчас это Яндекс-Доставка) для отслеживания пути доставочного заказа от начального статуса поиска внешнего курьера до финального статуса доставки заказа в руки клиенту. По мере изменения свойства [`RideStatus`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Brd_RideStatus.htm) официант может видеть, в какой стадии находится доставка заказа клиенту.
```

2022-08-17 21:56 UTC, zed220 commented on _posts/2022-08-16-ride.md
> +В свойстве [`Ride.ExternalId`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Brd_Ride_ExternalId.htm) хранится идентификатор данного заказа во внешней системе. В свойстве [`Ride
```suggestion
В свойстве [`Ride.ExternalId`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Brd_Ride_ExternalId.htm) хранится идентификатор данного заказа во внешней системе. С помощью свойства [`Ride.StatusDetails`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Brd_Ride_StatusDetails.htm) можно передать из внешней системы во фронт дополнительную информацию о поездке.
```

2022-08-18 21:46 UTC, zed220 commented on _posts/2022-08-16-ride.md
> +---
Сделай, пожалуйста, каждое предложение на новой строке. Можешь посмотреть, как в других местах это уже сделано.

2022-08-19 09:08 UTC, OlgaBelilovskaya commented on _posts/2022-08-16-ride.md
> +---
Сделала, спс. Посмотри пожалуйста.

2022-08-19 21:43 UTC, zed220 approved these changes

2022-08-23 10:07 UTC, vcpp requested changes

2022-08-23 10:07 UTC, vcpp commented on _posts/2022-08-16-ride.md
> +Поездка используется при работе с внешними курьерскими службами (сейчас это Яндекс-Доставка) для отслеживания пути доставочного заказа от начального статуса поиска внешнего курьера до финального стат
Яндекс Доставка без дефиса вроде бы? Мимо брендбука смотрится непривычно.

2022-08-23 10:07 UTC, vcpp commented on _posts/2022-08-16-ride.md
> +Для работы с поездками в [`IOperationService`](https://iiko.github.io/front.api.sdk/v8/html/Methods_T_Resto_Front_Api_IOperationService.htm) добавлены три метода.
Тут бы двоеточие и дальше список из трёх пунктов.

2022-08-23 15:25 UTC, OlgaBelilovskaya commented on _posts/2022-08-16-ride.md
> +Для работы с поездками в [`IOperationService`](https://iiko.github.io/front.api.sdk/v8/html/Methods_T_Resto_Front_Api_IOperationService.htm) добавлены три метода.
Сделала список.

2022-08-23 15:25 UTC, OlgaBelilovskaya commented on _posts/2022-08-16-ride.md
> +Поездка используется при работе с внешними курьерскими службами (сейчас это Яндекс-Доставка) для отслеживания пути доставочного заказа от начального статуса поиска внешнего курьера до финального стат
Убрала дефис.

2022-10-07 16:14 UTC, merged