RMS-54160 Добавлена новость о новых свойствах, связанных с настройкам…
iiko/front.api.doc pull request #121
Opened 2023-03-04 01:39 UTC by dgazimullin

…и дробного количества товаров

2023-03-04 15:41 UTC, ierof requested changes

2023-03-04 15:41 UTC, ierof commented on _posts/2023-03-03-fractional-amount-mode.md
> +[`IRestaurant.FractionalAmoutMode`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Organization_IRestaurant.htm),
опечатка -- FractionalAmountMode

2023-03-06 05:05 UTC, dgazimullin commented on _posts/2023-03-03-fractional-amount-mode.md
> +[`IRestaurant.FractionalAmoutMode`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Organization_IRestaurant.htm),
Исправил

2023-03-06 07:36 UTC, ierof approved these changes

2023-03-06 07:36 UTC, merged