Добавлена информация по изменениям введенных в структуру класса Exten…
iiko/front.api.doc pull request #137
Opened 2023-05-10 11:31 UTC by KMamedkulyev

…dedInputDialogSettings который передается в качестве параметра в ShowExtendedInputDialog()

2023-05-10 12:45 UTC, zed220 requested changes

2023-05-10 12:45 UTC, zed220 commented on v8/ru/ViewManager.md
> +В данной версии изменена структура класса настроек - [`ExtendedInputDialogSettings`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_ExtendedInputDialogSettings.htm), который переда
```suggestion
В версии V8 была изменена структура класса настроек - [`ExtendedInputDialogSettings`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_ExtendedInputDialogSettings.htm), который передается в качестве параметра в [`Диалоговое окно`](https://kmamedkulyev.github.io/front.api.doc/v6/ru/ViewManager.html) - [`ShowExtendedInputDialog()`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_UI_IViewManager_ShowExtendedInputDialog.htm). [`ExtendedInputDialogSettings.EnableNumericString`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_UI_ExtendedInputDialogSettings_EnableNumericString.htm) заменен на [`NumericInputMode`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm), который является типом `enum` состоящий из [`Disabled`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) - значение по умолчанию если не указан тип ввода, [`String`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) - ввод целых чисел, [`Decimal`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) - ввод дробных чисел. Для типа ввода дробных чисел - [`Decimal`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) добавлены свойства указания максимального значения - [`MaxDecimalValue`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_UI_ExtendedInputDialogSettings_MaxDecimalValue.htm), минимального значения - [`MinDecimalValue`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_UI_ExtendedInputDialogSettings_MinDecimalValue.htm), значения по умолчанию - [`DefaultDecimalValue`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_UI_ExtendedInputDialogSettings_DefaultDecimalValue.htm), с помощью которых можно задавать соответствующие ограничения. При выборе `String` или `Decimal`, пользователю будет предложено ввести целые числа или числа с дробью. В качестве поясняющего текста по дробным числам используется - [`ExtendedInputDialogSettings.TabTitleNumericString`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_UI_ExtendedInputDialogSettings_TabTitleNumericString.htm).
```

2023-05-10 12:45 UTC, zed220 commented on v8/ru/ViewManager.md
> +В данной версии изменена структура класса настроек - [`ExtendedInputDialogSettings`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_ExtendedInputDialogSettings.htm), который переда
Нужно для этого блока по-другому оформить список значений enum. Можно взять пример с любого списка, вот тут их много [http://iiko.github.io/front.api.doc/v7/ru/DateTimePopups.html](http://iiko.github.io/front.api.doc/v7/ru/DateTimePopups.html).

2023-05-10 12:45 UTC, zed220 commented on v8/ru/ViewManager.md
> +В данной версии изменена структура класса настроек - [`ExtendedInputDialogSettings`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_ExtendedInputDialogSettings.htm), который переда
Нужно каждое предложение начинать с новой строки. Выглядеть это будет как раньше, а ревьювить и предлагать исправления сильно проще.

2023-05-11 09:21 UTC, zed220 requested changes

2023-05-11 09:21 UTC, zed220 commented on v8/ru/ViewManager.md
> +В данной версии изменена структура класса настроек - [`ExtendedInputDialogSettings`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_ExtendedInputDialogSettings.htm), который переда
```suggestion
Начиная с версии V8, изменена структура класса настроек - [`ExtendedInputDialogSettings`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_ExtendedInputDialogSettings.htm), который передается в качестве параметра в [`Диалоговое окно`](https://kmamedkulyev.github.io/front.api.doc/v6/ru/ViewManager.html) - [`ShowExtendedInputDialog()`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_UI_IViewManager_ShowExtendedInputDialog.htm).
```

2023-05-11 09:21 UTC, zed220 commented on v8/ru/ViewManager.md
> +- [`Disabled`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) - значение по умолчанию если не указан тип ввода.
```suggestion
- [`Disabled`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) - значение по умолчанию, если не указан тип ввода.
```
Кстати, какое значение по умолчанию? Напиши туда же.

2023-05-11 09:21 UTC, zed220 commented on v8/ru/ViewManager.md
> +Для типа ввода дробных чисел - [`Decimal`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) добавлены свойства:
```suggestion
Для типа ввода дробных чисел [`Decimal`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) добавлены свойства:
```

2023-05-11 09:21 UTC, zed220 commented on v8/ru/ViewManager.md
> +При выборе определенного типа `String` или `Decimal` пользователю будет предложено ввести целые числа или числа с дробью.
```suggestion
При выборе `String` или `Decimal` пользователю будет предложено ввести целые числа или числа с дробью. 
```

2023-05-11 09:21 UTC, zed220 commented on v8/ru/ViewManager.md
> +    TabTitleNumericString = "Заголовок вкладки для ввода дробных числа",
Текст в коде не соответствует тексту на картинке.

2023-05-11 09:21 UTC, zed220 commented on v8/ru/ViewManager.md
> +В качестве поясняющего текста по дробным числам используется - [`ExtendedInputDialogSettings.TabTitleNumericString`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_UI_ExtendedInputDia
```suggestion
В качестве поясняющего текста по дробным числам используется [`ExtendedInputDialogSettings.TabTitleNumericString`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_UI_ExtendedInputDialogSettings_TabTitleNumericString.htm).
```

2023-05-11 09:21 UTC, zed220 commented on v8/ru/ViewManager.md
> +В качестве поясняющего текста по дробным числам используется - [`ExtendedInputDialogSettings.TabTitleNumericString`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_UI_ExtendedInputDia
А это точно используется только для дробных чисел?

2023-05-11 09:27 UTC, KMamedkulyev commented on v8/ru/ViewManager.md
> +В качестве поясняющего текста по дробным числам используется - [`ExtendedInputDialogSettings.TabTitleNumericString`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_UI_ExtendedInputDia
Не только для дробных, TabTitleNumericString используется для String и Decimal, если помнишь - решили не городить отдельный TabTitle для Decimal и использовать существующий.

2023-05-11 09:56 UTC, zed220 requested changes

2023-05-11 09:56 UTC, zed220 commented on v8/ru/ViewManager.md
> +- [`Disabled`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) - значение по умолчанию, если не указан тип ввода.
Не указано, какое значение является значением по умолчанию.

2023-05-11 09:56 UTC, zed220 commented on v8/ru/ViewManager.md
> +В качестве поясняющего текста по дробным числам используется [`ExtendedInputDialogSettings.TabTitleNumericString`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_UI_ExtendedInputDialo
```suggestion
В качестве поясняющего текста используется [`ExtendedInputDialogSettings.TabTitleNumericString`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_UI_ExtendedInputDialogSettings_TabTitleNumericString.htm).
```

2023-05-11 10:15 UTC, KMamedkulyev commented on v8/ru/ViewManager.md
> +- [`Disabled`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) - значение по умолчанию, если не указан тип ввода.
Disabled является значением по умолчанию - оно в тексте указано, получается если не указали ничего в NumericInputMode, то ничего и не отобразится, по умолчанию в NumericInputMode будет Disabled.

2023-05-11 10:25 UTC, zed220 commented on v8/ru/ViewManager.md
> +- [`Disabled`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) - значение по умолчанию, если не указан тип ввода.
Тогда так и напиши.

2023-05-11 10:30 UTC, KMamedkulyev commented on v8/ru/ViewManager.md
> +- [`Disabled`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) - значение по умолчанию, если не указан тип ввода.
![disabled](https://github.com/iiko/front.api.doc/assets/133098961/c244aea7-53af-49ca-832a-37cdb92d8b40)
Написано))

2023-05-11 11:42 UTC, zed220 commented on v8/ru/ViewManager.md
> +- [`Disabled`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_UI_NumericInputMode.htm) - значение по умолчанию, если не указан тип ввода.
"получается если не указали ничего в NumericInputMode, то ничего и не отобразится"
Предлагаю так и написать. Примерно так:
`Disabled - значение по умолчанию. Возможность ввода числовых значений выключена.`

2023-05-11 12:31 UTC, merged