RMS-54503 Новые возможности GetCashRegisterStatus
iiko/front.api.doc pull request #143
Opened 2023-06-01 07:56 UTC by dgazimullin

2023-06-01 07:58 UTC, dgazimullin commented
@ierof review pls

2023-06-08 20:12 UTC, ierof requested changes

2023-06-08 20:12 UTC, ierof commented on _posts/2023-05-30-cash-register-status-fields.md
> +Добавлена возможность получения дополнительных свойств с помощью [`IOperationService.GetCashRegisterStatus`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_IOperationService_GetCashRe
```suggestion
В API V8Preview6 добавлена возможность получения дополнительных свойств с помощью [`IOperationService.GetCashRegisterStatus`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_IOperationService_GetCashRegisterStatus.htm).
```

2023-06-19 06:52 UTC, ierof approved these changes

2023-06-19 06:52 UTC, merged