Новый метод RegisterExternalCompanyInfoSearchProvider RMS-54484
iiko/front.api.doc pull request #148
Opened 2023-07-08 11:43 UTC by OlgaBelilovskaya

2023-07-10 07:57 UTC, semenov-ch approved these changes

2023-09-23 23:22 UTC, vcpp requested changes

2023-09-23 23:22 UTC, vcpp commented on _posts/2023-07-07-RegisterExternalCompanyInfoSearchProvider.md
> +title: Новый метод RegisterExternalCompanyInfoSearchProvider
Вместо названия метода лучше сформулировать, какую задачу с помощью него можно решить. Например, «Загрузка реквизитов организации из внешнего сервиса».

2023-09-23 23:22 UTC, vcpp commented on _posts/2023-07-07-RegisterExternalCompanyInfoSearchProvider.md
> +Начиная с версии API V8Preview5, добавлен новый метод [`RegisterExternalCompanyInfoSearchProvider`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_IOperationService_RegisterExternalCo
По сути, получился перевод слов из имени метода с английского на русский. Чтобы это почувствовать, можно представить, как это предложение выглядело бы на английском: *`RegisterExternalCompanyInfoSearchProvider` allows to register external company info search provider*.

Надо постараться в первом абзаце кратко и ёмко сформулировать суть доработки, поскольку в общей ленте показывается только первый абзац, а также чтобы просматривающему ленту разработчику было проще понять, стоит ли открывать заметку или она не представляет для него интереса.

Я бы предложил так:
> Начиная с V8Preview5 можно упростить заполнение полей при редактировании организации. Пользователю будет достаточно ввести ИНН, далее плагин выполнит поиск во внешней системе и заполнит остальные реквизиты.

Имена методов, dto'шек и прочие технические подробности в следующих абзацах.

2023-09-23 23:22 UTC, vcpp commented on _posts/2023-07-07-RegisterExternalCompanyInfoSearchProvider.md
> +В аргументах RegisterExternalCompanyInfoSearchProvider передается callback-метод Func<string, ExternalCompanyInfo> getCompanyInfoCallback, принимающий на вход строку с ИНН искомой организации, и возв
Для читабельности хорошо бы куски кода, включая имена методов и типов, выделять моноширинным шрифтом с помощью обратного апострофа.
Также для читабельности хорошо бы сгруппировать предложения по смыслу в абзацы. Сейчас каждое предложение с новой строки отдельным абзацем, что [выглядит](https://olgabelilovskaya.github.io/front.api.doc/2023/07/07/RegisterExternalCompanyInfoSearchProvider.html) не очень..

2023-09-29 16:05 UTC, OlgaBelilovskaya commented on _posts/2023-07-07-RegisterExternalCompanyInfoSearchProvider.md
> +В аргументах RegisterExternalCompanyInfoSearchProvider передается callback-метод Func<string, ExternalCompanyInfo> getCompanyInfoCallback, принимающий на вход строку с ИНН искомой организации, и возв
сделала, спасиб

2023-09-29 16:06 UTC, OlgaBelilovskaya commented on _posts/2023-07-07-RegisterExternalCompanyInfoSearchProvider.md
> +Начиная с версии API V8Preview5, добавлен новый метод [`RegisterExternalCompanyInfoSearchProvider`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_IOperationService_RegisterExternalCo
Сделала.

2023-09-29 16:06 UTC, OlgaBelilovskaya commented on _posts/2023-07-07-RegisterExternalCompanyInfoSearchProvider.md
> +title: Новый метод RegisterExternalCompanyInfoSearchProvider
Спасибо, переделала.

2023-09-29 18:27 UTC, vcpp approved these changes

2023-09-29 18:28 UTC, merged