RMS-54742 Написать заметку о выпуске
iiko/front.api.doc pull request #149
Opened 2023-07-09 13:18 UTC by rgalk

2023-07-09 23:54 UTC, vcpp requested changes

2023-07-09 23:54 UTC, vcpp commented on _posts/2023-07-04-v8preview6-release.md
> +Таким образом срок жизни одной Preview-версии увеличивается на 3 месяца.
```suggestion
Таким образом, срок жизни одной Preview-версии увеличивается на 3 месяца.
```

2023-07-09 23:54 UTC, vcpp commented on versioning.md
> +| Версия iikoRMS | Выпуск версии API      | Удаление версии API        | Поддерживаемые зафиксированные версии                  |
Для чего могут понадобиться второй и третий столбцы?

2023-07-09 23:54 UTC, vcpp commented on versioning.md
> +Начиная с версии iikoRMS 8.5 момента цикл поддержки Preview-версий увеличивается: версия V8Preview4, которая была выпущена в 8.3, будет удалена лишь в 8.6, т.е. поддерживается в 8.3, 8.4, 8.5.
```suggestion
Начиная с версии iikoRMS 8.5 цикл поддержки Preview-версий увеличивается: версия V8Preview4, которая была выпущена в 8.3, будет удалена лишь в 8.6, т.е. поддерживается в 8.3, 8.4, 8.5.
```

2023-07-09 23:54 UTC, vcpp commented on _posts/2023-07-04-v8preview6-release.md
> +Версия V8Preview6 будет поддерживаться в 8.5, 8.6 и 8.7, а удаление произойдет в 8.8.
Я бы не стал писать про удаление, это теперь деталь реализации. Снаружи важно, что есть три версии, в которых V8Preview6 поддерживается, соответственно, во всех остальных не поддерживается.
На твоё усмотрение.

2023-07-09 23:54 UTC, vcpp commented on _posts/2023-07-04-v8preview6-release.md
> +Подробнее о версиях API [тут]({{ site.baseurl }}/versioning.html).
Могут возникнуть вопросы про LTS-версии. Даже если с ними всё по-прежнему, хорошо бы написать об этом явно.

2023-07-25 15:48 UTC, rgalk commented on _posts/2023-07-04-v8preview6-release.md
> +Подробнее о версиях API [тут]({{ site.baseurl }}/versioning.html).
+

2023-07-25 15:49 UTC, rgalk commented on _posts/2023-07-04-v8preview6-release.md
> +Версия V8Preview6 будет поддерживаться в 8.5, 8.6 и 8.7, а удаление произойдет в 8.8.
Убрал часть предложения про удаление.

2023-07-25 15:51 UTC, rgalk commented on versioning.md
> +| Версия iikoRMS | Выпуск версии API      | Удаление версии API        | Поддерживаемые зафиксированные версии                  |
Вернул таблицу в первоначальное состояние, убрал лишь колонку со статусом версии. Этак колонка мне всегда казалась неудобной, не говоря о том, что нужно было каждую версию вносить правки.

2023-07-26 00:54 UTC, vcpp requested changes

2023-07-26 00:54 UTC, vcpp commented on versioning.md
> +| V9Preview2  | 9.9              | 9.2      |
```suggestion
| V9Preview2  | 8.9              | 9.2      |
```

2023-07-26 08:59 UTC, ierof approved these changes

2023-07-26 21:05 UTC, merged