RMS-54798 Поправила ссылку и пару неточностей.
iiko/front.api.doc pull request #157
Opened 2023-10-12 09:40 UTC by OlgaBelilovskaya

RMS-54798 Описать новые поля, заполняемые при переносе доставки с точки на точку.

2023-10-12 13:17 UTC, semenov-ch requested changes

2023-10-12 13:17 UTC, semenov-ch commented on _posts/2023-10-06-MovedToFromDeliveryId.md
> +При переносе доставки с точки на точку старая доставка переходит в статус "Отменена", и на новой точке путем клонирования данных создается новая доставка. Поле [`MovedToDeliveryId`](https://iiko.gith
а вот тут уже кажется запятая лишняя, после "Отменена"?

2023-10-12 13:17 UTC, semenov-ch commented on _posts/2023-10-06-MovedToFromDeliveryId.md
> +Начиная с V8Preview7 в доставочный заказ [`IDeliveryOrder`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Orders_IDeliveryOrder.htm) добавлены новые свойства, заполняющиеся при
Неплохо бы сразу обозначить о каких полях пойдет речь в тексте ниже. Можно даже их выделить в список чтобы было понятнее и главное добавить ссылки как в тексте ниже.

2023-10-20 10:16 UTC, OlgaBelilovskaya commented on _posts/2023-10-06-MovedToFromDeliveryId.md
> +Начиная с V8Preview7 в доставочный заказ [`IDeliveryOrder`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Orders_IDeliveryOrder.htm) добавлены новые свойства, заполняющиеся при
Я раньше тоже так считала. Но теперь после комментариев Айрата в прошлой моей статье, в первом абзаце просто стараюсь суммировать основную мысль, что сделано, а во втором - его откроют только те, кому нововведение интересно и может понадобится, уже детали, с названиями с ссылками.

2023-10-20 10:24 UTC, OlgaBelilovskaya commented on _posts/2023-10-06-MovedToFromDeliveryId.md
> +При переносе доставки с точки на точку старая доставка переходит в статус "Отменена", и на новой точке путем клонирования данных создается новая доставка. Поле [`MovedToDeliveryId`](https://iiko.gith
Согласна. Убрала.

2023-10-26 11:23 UTC, semenov-ch approved these changes

2023-10-26 11:55 UTC, merged