RMS-53693 Документация: Обновить документацию по API
iiko/front.api.doc pull request #165
Opened 2023-12-19 11:08 UTC by DahurOuie

Создание доставки с полем адреса Line1.
Получение настроек адреса доставки.

2023-12-20 12:56 UTC, sparoq10 commented on _posts/2023-12-18-v8-address-line1-line2.md
> +*StreetId = f8aaf1ec-8f46-907f-9357-e4c27bab5f78* - Id пустой улицы в БД (одинаковый для всех баз).<br>
Привет. Мы не выставляем EmptyStreet как константу в апи, чтобы не заставлять людей её из документации копировать?)

2023-12-20 13:03 UTC, sparoq10 commented on _posts/2023-12-18-v8-address-line1-line2.md
> +*House = ""* - пустая строка или string.Empty, но отсутствие данного поля не допустимо.<br>
И вообще, если у нас столько "особенностей", что три поля повязаны такой зависимостью, почему бы не сделать конструктор/фабрику с корректным набором параметров?
public AddressDto(string line1, string flat/*и далее по списку*/)
{
    Line1 = line1;
    StreetId = EmptyStreetId;
    House = "";
    Flat = flat;
    // и далее по списку
}

public AddressDto(Guid streetId, string house, string flat /*и далее по списку*/)
{
    StreetId = streetId;
    House = house;
    Flat = flat;
    /*и далее по списку*/
}

Возможно, через private AddressDto(полный набор параметров) и вызов его через this(null, streetId, house, flat, etc.) и this(line1, EmptyStreetId, "", flat, etc.).

В общем, как-то облагородить, отразить зависимости эти в коде.

2023-12-20 13:07 UTC, sparoq10 commented on _posts/2023-12-18-v8-address-line1-line2.md
> +---
address-line1-line2.md намекало на наличие Line2, а про него ни слова.
Что решили с поддержкой этого международного формата?
Это повлияет на примеры конструкторов.:)

2023-12-22 02:25 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +*StreetId = f8aaf1ec-8f46-907f-9357-e4c27bab5f78* - Id пустой улицы в БД (одинаковый для всех баз).<br>
Нет, не выставляем. В плагине доставки оно отдельно вписывается. 
И лучше этот момент прописать так, чтобы его было ВИДНО и прочитано как можно большим количеством человек.

2023-12-22 02:28 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +*House = ""* - пустая строка или string.Empty, но отсутствие данного поля не допустимо.<br>
Сейчас эти зависимости скорее баг, чем фича. И, во избежание непонимания как делать, описано как формировать адрес. Позже это будет переделано и обязательные поля будут не нужны.

2023-12-22 02:29 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +---
Line2 актуально для UK. пока нет ни интерфейса (UI), ни какого-то вменяемого запроса.

2024-04-16 20:54 UTC, sparoq10 requested changes

2024-04-16 20:54 UTC, sparoq10 commented on _posts/2023-12-18-v8-addresssettings.md
> +[UseNewFormat](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Settings_AddressShowTypeSettings_UseNewFormat.htm) - использовать ли формат адреса доставки с полями Line1 и Line2.<
Понятно, что мы сейчас говорим о документации, а не о коде, который уже написан и написан весьма давно...
Но нельзя не сказать, что NewFormat? А в следующей версии NotSoNewFormat, а в следующей OldFormat. Теперь главное не придумать ещё пару более новых форматов, чтобы не заводить NewNewFormat, VeryNewFormat, YetAnotherNewFormat... Называть надо осмысленно. Если там суть в Line1 и Line2, хотя бы InternationalFormat, первое, что в голову пришло. Мало ли наделенных смыслом названий можно было бы придумать, нежели NewFormat...

2024-04-16 20:54 UTC, sparoq10 commented on v8/ru/AddressSettings.md
> +[AddressShowTypeSettings](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Settings_AddressShowTypeSettings.htm) addressShowTypeSettings = restaurant.[AddressShowTypeSettings](http
Ссылки в коде выглядят на любителя. Лучше отдельно код, отдельно описание со ссылками. А для восприятия кода надо разметку ``` натянуть, а не br.

2024-05-27 16:43 UTC, OlgaBelilovskaya commented on _posts/2022-12-12-change-ride-status-changes.md
> +Начиная с API V8Preview3 при завершении поездки (вызов метода [`ChangeRideStatus`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_Editors_IEditSession_ChangeRideStatus.htm) со статусо
Битая ссылка на ChangeRideStatus.

2024-05-28 11:08 UTC, OlgaBelilovskaya commented on _posts/2022-12-12-change-ride-status-changes.md
> +
Лишняя запятая после Также.

2024-05-28 11:16 UTC, OlgaBelilovskaya commented on _posts/2022-12-12-change-ride-status-changes.md
> +Теперь, при вызове этого метода, в фактическое время доставки [`ActualDeliverTime`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Orders_IDeliveryOrder_ActualDeliverTime.htm) за
Слей лучше этот абзац вместе с предыдущим. Т.к. сейчас кажется, что 1. изменено поведение метода SetDeliveryDelivered, и 2. при вызове Этого (какого??) метода в ActualDeliverTime записывается время. Короче, мне кажется это должно быть в 1 абзаце. Если не согласен, забиваем.

2024-05-28 13:46 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +title: API V8 Создание доставки с полем адреса Line1.
Из заголовка убрать "API V8", заголовок должен начинаться с "Создание .."

2024-05-29 14:36 UTC, OlgaBelilovskaya requested changes
Леш, основное, в папке _posts  лежат короткие статейки на тему "что нового", а в v8\ru - статьи-руководства более подробные. Поэтому весь код с примерами формирования стоит оставить в файлах, относящихся к  v8\ru. А в _posts в статейках оставить просто описания с ссылками, но без примеров кода.
При этом не убирай тупо, а посмотри что получается нормально и те и другие статьи, что законченно, похоже на остальные файлы рядом по стилю.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +---
добавить строку (посмотри как в других статьях теперь таги в начале ставятся тоже):
tags: v8

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +В API V8 появилась возможность создавать доставки, где адрес формируется с помощью поля **Line1**, вместо полей город, улица, дом, корпус.<br>
1. Вот так не более по-русски звучит? Не настаиваю
"В API V8 появилась возможность создавать доставки, где адрес, вместо полей город, улица, дом, корпус, формируется с помощью поля Line1."
2. Line1 надо вместо \* \* поместить в одинарные кавычки \` \`, и прилепить какую-то ссылку стоит.
Вот чтобы было вот так типа:
[`Line1`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Brd_IAddress_Line1.htm).

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +**Line1** - это часть адреса, которая указывает как найти объект на карте при геокодировании.<br>
1. Вместо \*\* обычно тут используют \` \` .
2. Запятая перед "как"

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +**Пример:** Москва, Варшавское шоссе, д.86, корп.2
Считаю, что надо убрать \*\*  вокруг "Пример", я смотрю нигде жирным шрифтом в доках не пишут.. А "Москва, Варшавское шоссе, д.86, корп.2" можно курсивом.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +title: API V8 Создание доставки с полем адреса Line1.
Из заголовка убрать "API V8", заголовок должен начинаться с "Создание .."

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +пункт "*Использовать новый формат адреса*" и выбрать ниже режим: *Поля "Куда везти", "квартира", "этаж"....*<br>
1. Поточнее название настройки и убрать уточнение, где настройки расположены:
(*Администрирование -> Настройки торгового предприятия -> Основные настройки*)  в разделе "*Формат адреса доставки*
пункт "*Использовать новый формат адреса*" и выбрать ниже режим: *Поля "Куда везти", "квартира", "этаж"...
2. \<br> лишнее имхо. Я бы слила в один абзац без перехода на новую строку.
3. перед \<br> должно быть 3 точки - сейчас 4.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +Для формирования доставки нужно включить в настройках ресторана
Для формирования АДРЕСА

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +После перезапустить iikoFront и iikoOffice для применения настроек отображения адресов.
1. После Этого Нужно перезапустить ...
2. А точно надо перезапускать фронт? Оно и без перезапуска подхватывается мне кажется. А бэк точно надо перезапускать? Про него я не знаю.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +**ОСОБЕННОСТЬ ФОРМИРОВАНИЯ ЗАПРОСА:**<br>
\<br> тоже лишнее, посмотри в других статьях, у нас ставят по-моему пустую строку для перехода на новую строку.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +>При создании доставки в адресе (Address) **должны** быть заполнены поля **StreetId и House** следующим образом:<br>
1. Зачем тут форматирование как цитата?
2. \<br> лишнее, нужно пропустить строку.
3. Так более по русски. Плюс надо заменить \*\* на \` , плюс надо гиперссылку на адрес:
"При создании доставки поля адреса ([`AddressDto`](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Brd_AddressDto.htm)) `StreetId` и `House`   **должны** быть заполненыс следующим образом:"

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +*StreetId = f8aaf1ec-8f46-907f-9357-e4c27bab5f78* - Id пустой улицы в БД (одинаковый для всех баз).<br>
1. опять \<br>
2. Поменять * на ` :

`StreetId = f8aaf1ec-8f46-907f-9357-e4c27bab5f78`

3. Это точно актуально сейчас? Ты там менял немного всю эту логику недавно, посмотри на этот счет, может надо будет актуализировать уже ((.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +*House = ""* - пустая строка или string.Empty, но отсутствие данного поля не допустимо.<br>
1. Недопустимо - вместе.
2. Поменять \* на \` :

`House = ""` или `House = string.Empty`. Отсутствие данного поля недопустимо.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +**Пример формирования адреса:**<br>
1. пустая строка вместо \<br>
2. Я бы убрала bold вокруг.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +---
добавить "tags: v8"

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +В API V8 появилась возможность получать настройки адресов для корректной работы с созданием доставки.<br>
заменить везде \<br> на пустую строку как в других доках.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +Для удобства разработчика и реализации других схем плагин получает все доступные поля настроек.
Предлагаю сократить, тк это почти риторика. как вариант:
"Данный функционал реализован для того, чтобы при создании доставки плагин знал, можно ли использовать адреса с полями Line1 и Line2 или нет."

И данный абзац сдвинуть вверх, пусть идет сразу после абзаца "В API V8 появилась возможность получать настройки адресов для корректной работы с созданием доставки."

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +Как получить настройки:<br>
"Как получить новые настройки адреса доставки:"

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +>...<br>
Зачем тут цитирование? Надо убрать.
Вместо этого поместить код в \` \`.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +В **addressShowTypeSettings** будут следующие поля:<br>
addressShowTypeSettings в \` вместо болд

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +[UseNewFormat](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Settings_AddressShowTypeSettings_UseNewFormat.htm) - использовать ли формат адреса доставки с полями Line1 и Line2.<
Поместить ссылку в \` \`.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +[UseLiveSearch](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Settings_AddressShowTypeSettings_UseLiveSearch.htm) - использовать ли живой поиск (DaData) для добавления адресов д
Поместить ссылку в \` \`.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +[AddressShowType](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Settings_AddressShowTypeSettings_AddressShowType.htm) - Какой тип отображения адреса доставки ипользуется на iiko
1. Поместить ссылку в \` \`.
2. Какой - с маленькой буквы
3. В iikoFront и iikoOffice.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +CITY - формат адреса с полями «Куда везти»(line1), «Подъезд», «Этаж» и т.д.<br>
1. «Куда везти» (Line1)
2. Везде "Формат" с большой, а тут с маленькой. Сделай одинаково везде, может и с маленькой лучше.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +---
Я вот пытаюсь понять, вот ниже есть копия данного файла в папке v8/ru - 
https://github.com/iiko/front.api.doc/pull/165/files?short_path=b28ebdb#diff-b28ebdb70675778b44376890aac87c671724e172f8e731f5d584c44eb459376a
и я так понимаю, тот файл как раз как бы статья в помощь разрабам, а не просто короткое в change.log. Может тогда код вынесем туда, а общие слова оставим тут? Вот все, что ниже "Особенности формирования запроса" чтобы ушло в  v8/ru, а отсюда из change.log убрать это.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +---
Общая ремарка - ниже в папке v8/ru есть файл AddressSettings
https://github.com/iiko/front.api.doc/pull/165/files#diff-b16c6a04566d05cd51a0ff6f38657df595dc2ae53f55bf1c415bb4bc64999249
вот видимо он есть общая статья в помощь разрабам, и в нем должен быть весь код из данной статьи, предназначенной для change.log. Т.е. все, что начинается с "Как получить настройки:", надо оставить в статье в v8/ru, а отсюда это наверное надо убрать.

2024-05-29 14:36 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +
Тут добавить текст на новой строке с пропуском строки, чтото типа:

Для этого в настройки ресторана` [IRestaurant](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Organization_IRestaurant.htm)` было добавлено свойство `[AddressShowTypeSettings](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Organization_IRestaurant_AddressShowTypeSettings.htm)`.

2024-05-31 11:55 UTC, DahurOuie commented on _posts/2022-12-12-change-ride-status-changes.md
> +Начиная с API V8Preview3 при завершении поездки (вызов метода [`ChangeRideStatus`](https://iiko.github.io/front.api.sdk/v8/html/M_Resto_Front_Api_Editors_IEditSession_ChangeRideStatus.htm) со статусо
+

2024-05-31 11:55 UTC, DahurOuie commented on _posts/2022-12-12-change-ride-status-changes.md
> +
++

2024-05-31 12:21 UTC, DahurOuie commented on _posts/2022-12-12-change-ride-status-changes.md
> +Теперь, при вызове этого метода, в фактическое время доставки [`ActualDeliverTime`](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Orders_IDeliveryOrder_ActualDeliverTime.htm) за
++

2024-05-31 12:21 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +---
++

2024-05-31 12:21 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +---
++

2024-05-31 12:21 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +В API V8 появилась возможность создавать доставки, где адрес формируется с помощью поля **Line1**, вместо полей город, улица, дом, корпус.<br>
++

2024-05-31 12:21 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +**Пример:** Москва, Варшавское шоссе, д.86, корп.2
++

2024-05-31 12:21 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +пункт "*Использовать новый формат адреса*" и выбрать ниже режим: *Поля "Куда везти", "квартира", "этаж"....*<br>
++

2024-05-31 12:32 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +После перезапустить iikoFront и iikoOffice для применения настроек отображения адресов.
1. ++
2. да, надо

2024-05-31 12:32 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +**ОСОБЕННОСТЬ ФОРМИРОВАНИЯ ЗАПРОСА:**<br>
++

2024-05-31 12:32 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +>При создании доставки в адресе (Address) **должны** быть заполнены поля **StreetId и House** следующим образом:<br>
1. чтобы был сдвиг вправо.
2. так оно с новой строки
3.++

2024-05-31 12:32 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +*StreetId = f8aaf1ec-8f46-907f-9357-e4c27bab5f78* - Id пустой улицы в БД (одинаковый для всех баз).<br>
1. да, опять для новой строки
2. ++
3. да, пусть так будет.

2024-05-31 12:32 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +**Пример формирования адреса:**<br>
1. ++
2. так лучше видно ключевые слова.

2024-05-31 12:32 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +---
++

2024-05-31 13:09 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +Для формирования доставки нужно включить в настройках ресторана
я убрал из анонса вообще всё, что ниже примера адреса

2024-05-31 13:09 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +В API V8 появилась возможность получать настройки адресов для корректной работы с созданием доставки.<br>
++

2024-05-31 13:09 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +
++

2024-05-31 13:09 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +>...<br>
ссылки работать не будут

2024-05-31 13:09 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +[AddressShowTypeSettings](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Settings_AddressShowTypeSettings.htm) addressShowTypeSettings = restaurant.[AddressShowTypeSettings](http
код никто копировать не будет, а вот нажимать на классы и пр. будут

2024-05-31 13:09 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +[UseNewFormat](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Settings_AddressShowTypeSettings_UseNewFormat.htm) - использовать ли формат адреса доставки с полями Line1 и Line2.<
++

2024-05-31 13:09 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +В **addressShowTypeSettings** будут следующие поля:<br>
++

2024-05-31 13:09 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +[UseLiveSearch](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Settings_AddressShowTypeSettings_UseLiveSearch.htm) - использовать ли живой поиск (DaData) для добавления адресов д
++

2024-05-31 13:09 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +[AddressShowType](https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Settings_AddressShowTypeSettings_AddressShowType.htm) - Какой тип отображения адреса доставки ипользуется на iiko
++

2024-05-31 13:09 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +CITY - формат адреса с полями «Куда везти»(line1), «Подъезд», «Этаж» и т.д.<br>
++

2024-05-31 13:11 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +Для удобства разработчика и реализации других схем плагин получает все доступные поля настроек.
1. Пусть будет.
2. зачем?

2024-06-05 14:07 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +**Line1** - это часть адреса, которая указывает как найти объект на карте при геокодировании.<br>
+ вообще убрал эти строки

2024-06-05 14:07 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +title: API V8 Создание доставки с полем адреса Line1.
++

2024-06-05 14:12 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
> +*House = ""* - пустая строка или string.Empty, но отсутствие данного поля не допустимо.<br>
++ убрано тут. в основном файле поменял.

2024-06-05 14:25 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +Как получить настройки:<br>
++

2024-06-05 14:28 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +---
++

2024-06-05 16:40 UTC, OlgaBelilovskaya requested changes

2024-06-05 16:40 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
> +---title: Создание доставки с полем адреса Line1.layout: defaulttags: v8---В API V8 появилась возможность создавать доставки, где адрес, вместо полей город, улица, дом, корпус, формируется с п
чтото таки не то с форматированием. Посмотри, этот файл и следующий отличаются от самого первого. Первый - норм. А эти два другие. Вот вставлю скриншотов для сравнения
![image](https://github.com/iiko/front.api.doc/assets/33130888/3a1ead57-fc81-44a4-9815-6370c4c65365)
![image](https://github.com/iiko/front.api.doc/assets/33130888/8969fd2f-c7df-4fb3-afed-243f29d7aba1)
![image](https://github.com/iiko/front.api.doc/assets/33130888/d57e353c-9e0a-42c0-9daa-55d1ed8e5d30)
![image](https://github.com/iiko/front.api.doc/assets/33130888/6813a3b0-2d82-48d9-bbd8-2484141a649e)
![image](https://github.com/iiko/front.api.doc/assets/33130888/3696fba1-1e2c-4d29-b762-1c5486641d26)

2024-06-05 16:40 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +Для удобства разработчика и реализации других схем плагин получает все доступные поля настроек.
Ну оно нечитабельно. И второе предложение как бы очевидное, понятно, что мы выставили наружу настройки для того, чтобы программисты их видели и пользовались.
2. Надо подвинуть, чтобы схема статьи была <Что и зачем сделано><Как пользоваться - примеры кода>

2024-06-05 16:40 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +---title: Получение настроек адреса доставки.layout: defaulttags: v8---В API V8 появилась возможность получать настройки адресов для корректной работы с созданием доставки.Для этого в настро
1. я не понимаю что с форматированием. Все показывается в одной строке. Надо сделать так же, как в соседних файлах, вот скрин смотри, тут твое и соседний файл. <br> заменить на пустые строки, как там. Очень сложно писать комменты к строкам, когда строка одна).
2. "Как получить новые настройки адреса доставки::" - тут лишнее двоеточие.
3. Все, что в разделе "Как получить новые настройки адреса доставки::" - это пример кода. Я бы убрала гиперссылки из этого кода, и таки убрала бы цитирование, оформи как код, это будет нормально читаться имхо. Гиперссылки убрать точно надо, про отступ ты сказал что не хочешь, ну смотри.
4. "INTERNATIONAL -Стиль адреса в Великобритании с Line1 и Line2" - пробел перед Стиль
5. "NOPOSTCODE - Стиль адреса ОАЭ." - лишняя точка в конце, тк в других пунктах точек нет

2024-06-05 16:40 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +>...<br>
Вот надо убрать ссылки из примеров кода имхо. Ссылки теперь есть в предложении выше.

2024-06-05 16:40 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +[AddressShowTypeSettings](https://iiko.github.io/front.api.sdk/v8/html/T_Resto_Front_Api_Data_Settings_AddressShowTypeSettings.htm) addressShowTypeSettings = restaurant.[AddressShowTypeSettings](http
Я не согласна. Копировать именно буду код. А ссылки будут выше, в них и кликнут. А тут можно оформить как код. Но я писала в другом месте это.

2024-06-05 16:40 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +INTERNATIONAL -Стиль адреса в Великобритании с Line1 и Line2<br>
пробел перед Стиль.

2024-06-05 16:40 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +Типы отображения адресов:<br>
убрать <br> из всего раздела этого из всех пунктов.

2024-06-05 16:40 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +NOPOSTCODE - Стиль адреса ОАЭ.<br>
убрать точку в конце - в других пунктах точек неет.

2024-06-05 16:40 UTC, OlgaBelilovskaya commented on v8/ru/AddressWithLine1.md
> +---title: Создание доставки с полем адреса Line1.layout: defaulttags: v8---В API V8 появилась возможность создавать доставки, где адрес, вместо полей город, улица, дом, корпус, формируется с п
0. Поправить форматирование как я уже писала в комменте к другому файлу.
1. Убрать уточнение о местонахождение настроек на странице. Чтобы стало так:

"Для формирования адреса нужно включить в настройках ресторана (Администрирование -> Настройки торгового предприятия -> Основные настройки) пункт "Использовать новый формат адреса" и выбрать ниже режим: Поля "Куда везти", "квартира", "этаж"... После этого нужно перезапустить iikoFront и iikoOffice для применения настроек отображения адресов."

2. "При создании доставки - убрать кавычку
3. При создании доставки поля адреса (AddressDto) StreetId и House должны - 

StreetId и House  сделать гиперссылками на  https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Brd_AddressDto_StreetId.htm
https://iiko.github.io/front.api.sdk/v8/html/P_Resto_Front_Api_Data_Brd_AddressDto_House.htm

2024-07-12 09:48 UTC, OlgaBelilovskaya requested changes
Нужны исправления.

2024-07-12 09:48 UTC, OlgaBelilovskaya commented on _posts/2023-12-18-v8-address-line1-line2.md
Смотри, у тебя как будто перепутан контент файлов
2023-12-18-v8-address-line1-line2.md и 2023-12-18-v8-addresssettings.md
То, что сейчас лежит в 2023-12-18-v8-addresssettings.md, должно быть в этом файле 2023-12-18-v8-address-line1-line2.md . А в 2023-12-18-v8-addresssettings.md должно быть про настройи ресторана, ты чтото не то стер в какойто из итераций.

2024-07-12 09:48 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +...
Многоточие здесь и после блока кода не нужно

2024-07-12 09:48 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +AddressShowTypeSettings addressShowTypeSettings = restaurant.AddressShowTypeSettings;<br>
<br> в конце сроки осталась

2024-07-12 09:48 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +LEGACY - Формат адреса с полями «Город», «Улица», «Дом», «Корпус»
Нужно разметить перечисление типов с помощью
- 
чтобы выглядело пунктами. Смотри как сделано, например. здесь 
v7/ru/DateTimePopups.md

2024-07-12 09:48 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +INTERNATIONAL -Стиль адреса в Великобритании с Line1 и Line2
Пробел поставить перед Стиль

2024-07-12 09:48 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +CITY - Формат адреса с полями «Куда везти»(Line1), «Подъезд», «Этаж» и т.д.
Пробел поставить перед (Line1)

2024-07-12 09:48 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +Для чего может пригодиться данный функционал:
Это пояснение про для чего может пригодиться функционал избыточно имхо.
Максимум можно вот так имхо, покороче:
_Данный функционал может пригодиться для того, чтобы при создании доставки на iikoFront плагин понимал, может ли он использовать для создания адреса доставки поля Line1 и Line2 или нет._

2024-07-12 09:48 UTC, OlgaBelilovskaya commented on v8/ru/AddressWithLine1.md
> +(`Администрирование -> Настройки торгового предприятия -> Основные настройки`) на главной странице в разделе "`Формат адреса доставки`"(внизу страницы настроек)
1. _на главной странице_ надо убрать, там нет главной страницы в разделе "Основные настройки"
2. _(внизу страницы настроек)_ надо убрать, это лишнее, я писала уже. Этот пункт может оказаться и не внизу, если добавят новые настройки в бэк

2024-07-12 09:48 UTC, OlgaBelilovskaya commented on v8/ru/AddressSettings.md
> +title: Получение настроек адреса доставки.
Точка в конце не нужна

2024-07-12 09:48 UTC, OlgaBelilovskaya commented on v8/ru/AddressWithLine1.md
> +title: Создание доставки с полем адреса Line1.
Точка в конце не нужна

2024-07-12 09:48 UTC, OlgaBelilovskaya commented on v8/ru/AddressWithLine1.md
> +пункт "`Использовать новый формат адреса`" и выбрать ниже режим: Поля `"Куда везти", "квартира", "этаж"...`
_Поля_ не попало в форматирование, его нужно внутрь ` перенести

2025-02-11 09:57 UTC, DahurOuie commented on _posts/2023-12-18-v8-address-line1-line2.md
Поменял контент местами.

2025-02-26 13:20 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +Для чего может пригодиться данный функционал:
++

2025-02-26 13:20 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +INTERNATIONAL -Стиль адреса в Великобритании с Line1 и Line2
++

2025-02-26 13:20 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +title: Получение настроек адреса доставки.
++

2025-02-26 13:20 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +...
++

2025-02-26 13:20 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +AddressShowTypeSettings addressShowTypeSettings = restaurant.AddressShowTypeSettings;<br>
++

2025-02-26 13:20 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +LEGACY - Формат адреса с полями «Город», «Улица», «Дом», «Корпус»
++

2025-02-26 13:20 UTC, DahurOuie commented on v8/ru/AddressSettings.md
> +CITY - Формат адреса с полями «Куда везти»(Line1), «Подъезд», «Этаж» и т.д.
++

2025-02-26 13:20 UTC, DahurOuie commented on v8/ru/AddressWithLine1.md
> +title: Создание доставки с полем адреса Line1.
++

2025-02-26 13:20 UTC, DahurOuie commented on v8/ru/AddressWithLine1.md
> +(`Администрирование -> Настройки торгового предприятия -> Основные настройки`) на главной странице в разделе "`Формат адреса доставки`"(внизу страницы настроек)
++

2025-02-26 13:20 UTC, DahurOuie commented on v8/ru/AddressWithLine1.md
> +пункт "`Использовать новый формат адреса`" и выбрать ниже режим: Поля `"Куда везти", "квартира", "этаж"...`
++

2025-02-26 13:22 UTC, OlgaBelilovskaya approved these changes

2025-02-26 13:22 UTC, OlgaBelilovskaya approved these changes

2025-02-26 13:23 UTC, OlgaBelilovskaya approved these changes

2025-02-26 13:23 UTC, OlgaBelilovskaya approved these changes

2025-02-26 13:23 UTC, OlgaBelilovskaya approved these changes

2025-02-27 08:48 UTC, merged