RMS-55974 and RMS-55972
iiko/front.api.doc pull request #175
Opened 2024-03-06 22:41 UTC by andrey-nasonov

2024-03-07 08:58 UTC, ierof requested changes

2024-03-07 08:58 UTC, ierof commented on _posts/2024-03-06-get-kitchen-order-by-order.md
> +В API V9Preview1 добавлен метод [`TryGetKitchenOrderByOrder`](https://iiko.github.io/front.api.sdk/v9/html/M_Resto_Front_Api_IOperationService_TryGetKitchenOrderByOrder.htm) позволяющий вернуть кухон
```suggestion
В API V9Preview1 добавлен метод [`TryGetKitchenOrderByOrder`](https://iiko.github.io/front.api.sdk/v9/html/M_Resto_Front_Api_IOperationService_TryGetKitchenOrderByOrder.htm) позволяющий вернуть кухонный заказ для обычного заказа. В случае, если кухонный заказ не был создан для этого заказа в данной группе, будет возвращено значение `null`.
```

2024-03-07 08:58 UTC, ierof commented on _posts/2024-03-06-get-kitchen-orders-param.md
> +Если передан параметр `true`, вернутся все кухонные заказы с заполненным полем [`IKitchenOrder.ExternalData`](https://iiko.github.io/front.api.sdk/v9/html/P_Resto_Front_Api_Data_Kitchen_IKitchenOrder
тут можно добавить, каким тогда образом, если был передан false, можно при необходимости получать  ExternalData

2024-03-07 09:38 UTC, ierof approved these changes

2024-03-07 09:39 UTC, merged

2024-03-11 15:19 UTC, sparoq10 commented on _posts/2024-03-06-get-kitchen-orders-param.md
> +Если поле [`IKitchenOrder.ExternalData`](https://iiko.github.io/front.api.sdk/v9/html/P_Resto_Front_Api_Data_Kitchen_IKitchenOrder_ExternalData.htm) `null`, то для получения внешних данных плагинов,
Согласование поехало, внешних данных плагинов, записанныХ в кухонный заказ.

2024-03-11 15:21 UTC, sparoq10 commented on _posts/2024-03-06-get-kitchen-orders-param.md
> +В API V9Preview1 добавлен опциональный параметр для метода [`GetKitchenOrders`](https://iiko.github.io/front.api.sdk/v9/html/M_Resto_Front_Api_IOperationService_GetKitchenOrders.htm) принимает значен
Несогласованное предложение:
>> В API V9Preview1 добавлен опциональный параметр для метода GetKitchenOrders принимает значение `true`, либо `false`.
Во-первых, надо согласовать предложение. Во-вторых, хочется видеть название параметра явно в тексте новости. Завтра добавим второй параметр, будет вообще непонятно, про какой из них статья. У него название есть, семантически подобранное, как раз чтобы всем всё было понятно.)

2024-03-11 15:34 UTC, sparoq10 commented on _posts/2024-03-06-get-kitchen-orders-param.md
> +Если передан параметр `true`, вернутся все кухонные заказы с заполненным полем [`IKitchenOrder.ExternalData`](https://iiko.github.io/front.api.sdk/v9/html/P_Resto_Front_Api_Data_Kitchen_IKitchenOrder
И да, минус — это не тире. Тире — это тире.

2024-03-11 15:41 UTC, sparoq10 commented on _posts/2024-03-06-get-kitchen-orders-param.md
> +Если передан параметр `true`, вернутся все кухонные заказы с заполненным полем [`IKitchenOrder.ExternalData`](https://iiko.github.io/front.api.sdk/v9/html/P_Resto_Front_Api_Data_Kitchen_IKitchenOrder
с полем ExternalData, равным `null` — запятая потерялась.
Наверное, я бы предпочел вообще вариант без null: некрасивый он — а что-нибудь вроде "с незаполненным полем ExternalData". 
Аналогично ниже: фразу "Если поле IKitchenOrder.ExternalData null" так и хочется как минимум расширить до полной версии "Если поле IKitchenOrder.ExternalData равно null/не задано", а как максимум уйти от технического языка про поле. У нас была статья про добавление параметра, который бы заполнил это поле всем, мы сейчас хотим дать совет, как можно получить это поле для конкретного заказа, если мы не хотим получать всё для всех. Поэтому скорее просится отсылка на "если при получении заказов внешние данные плагинов не были запрошены, их всегда можно получить методом TryGetKitchenOrderExternalDataByKey".

2024-03-11 19:54 UTC, andrey-nasonov commented
https://github.com/iiko/front.api.doc/pull/176