RMS-56084
iiko/front.api.doc pull request #177
Opened 2024-03-21 08:36 UTC by vkotelevskiy

2024-03-28 09:56 UTC, ierof requested changes

2024-03-28 09:56 UTC, ierof commented on _posts/2024-03-20-sampleplugin-update.md
> +В SamplePlugin были обновлены методы AddProduct и AddCompoundItem, используемые для добавления в заказ обычных и составных блюд. Эти методы демонстрируют механизм добавления в заказ блюд, требующих у
Хорошо бы выложить актуальный SamplePlugin тоже. 
Например, на v9preview1 в https://github.com/iiko/front.api.sdk/tree/master/sample
И в статье сослаться на код из этого проекта

2024-04-12 12:26 UTC, vkotelevskiy commented on _posts/2024-03-20-sampleplugin-update.md
> +В SamplePlugin были обновлены методы AddProduct и AddCompoundItem, используемые для добавления в заказ обычных и составных блюд. Эти методы демонстрируют механизм добавления в заказ блюд, требующих у
Исправил.

2024-04-12 13:30 UTC, ierof approved these changes

2024-04-12 13:30 UTC, merged