RMS-56340
iiko/front.api.doc pull request #192
Opened 2024-04-17 14:03 UTC by dterpal

RMS-56340

2024-04-18 07:59 UTC, ierof requested changes

2024-04-18 07:59 UTC, ierof commented on _posts/2024-04-17-SampleRazorRunner.md
> +title: Пример использования Razor`а в API
Лучше "Шаблонизация через RazorEngine для печатных форм"
Потому что у нас и так документация по API

2024-04-18 07:59 UTC, ierof commented on _posts/2024-04-17-SampleRazorRunner.md
> +---
лучше не в `_posts`, а в папку v8

2024-04-18 07:59 UTC, ierof commented on _posts/2024-04-17-SampleRazorRunner.md
> +На гитлабе был выложен новый пример [`SampleRazorRunner`](https://github.com/iiko/front.api.sdk/tree/master/sample/v8/Resto.Front.Api.SampleRazorRunner), который показывает возможности использования
не в гитлабе, 
Можно просто "Опубликован новый пример"

2024-04-18 07:59 UTC, ierof commented on _posts/2024-04-17-SampleRazorRunner.md
> +	1. Первый аргумент restoApiAssemblyToUse - обязательный. Перед компиляцией шаблона, который использует API методы из Resto.Front.Api, необходимо для компилятора указать, какая именно версия API буде
предложение составлено сложно, попробовать переформулировать

2024-04-18 07:59 UTC, ierof commented on _posts/2024-04-17-SampleRazorRunner.md
> +	2. Второй аргумент - необязательный. Список дополнительных сборок следовать указывать, если внутри шаблона будут использоваться какие-либо дополнительные данные, методы, на использование библиотек к
"Второй аргумент - необязательный" -- но по текущему коду оно обязательно :) Я поправлю код.

2024-04-18 07:59 UTC, ierof commented on _posts/2024-04-17-SampleRazorRunner.md
> +	2. Второй аргумент - необязательный. Список дополнительных сборок следовать указывать, если внутри шаблона будут использоваться какие-либо дополнительные данные, методы, на использование библиотек к
второе предложение не согласновано

2024-04-18 07:59 UTC, ierof commented on _posts/2024-04-17-SampleRazorRunner.md
> +---
ещё замечание ко всему файлу -- лучше размечать код через \`

2024-04-18 07:59 UTC, ierof commented on _posts/2024-04-17-SampleRazorRunner.md
> +Также пример имеет простое окно, позволяющее динамически задавать шаблон и видеть полученный результат или сведения об ошибках. Изначально в SampleRazorRunner приложен пример разметки Razor - RazorTe
Тут можно скриншот окна добавить.

2024-04-18 07:59 UTC, ierof commented on _posts/2024-04-17-SampleRazorRunner.md
> +Также пример имеет простое окно, позволяющее динамически задавать шаблон и видеть полученный результат или сведения об ошибках. Изначально в SampleRazorRunner приложен пример разметки Razor - RazorTe
И ещё тут надо добавить что-то типа:

Если вы хотите использовать данный механизм в своём плагине, можете скопировать такой-то файл as is и указать такую-то секцию в app.config

2024-04-18 07:59 UTC, ierof commented on _posts/2024-04-17-SampleRazorRunner.md
> +Далее будет представлен простой пример использования данного функционала:
пример кода лучше унести в самый низ статьи.

2024-04-18 07:59 UTC, ierof commented on _posts/2024-04-17-SampleRazorRunner.md
> +			    var result = RazorRunner.RunCompile(razorTemplate, model);
По самой задаче -- поняла, что кажется это каждый раз будет работать долго, потому что скомпилированные шаблоны не кэшируются. Можем ли мы отдельно run, отдельно compile?

И потом в этой статье описать, что если текст шаблона не менялся, его лучше кэшировать.

2024-04-19 08:40 UTC, ierof requested changes

2024-04-19 08:40 UTC, ierof commented on _posts/2024-04-17-SampleRazorRunner.md
> +---
этот файл можно стереть

2024-04-19 08:44 UTC, dterpal commented on _posts/2024-04-17-SampleRazorRunner.md
> +---
Да, я в следующем комите удалил его.
А нет, я не запушил. мда уж

2024-04-19 08:55 UTC, ierof approved these changes

2024-04-19 08:55 UTC, ierof commented
Мердж будет после публикации проверенного примера

2024-04-26 08:34 UTC, merged