RMS-55817 Front Api: Versioned entity was modified before actions exe…
iiko/front.api.doc pull request #204
Opened 2024-07-08 09:22 UTC by GulnaraBikbova

2024-07-15 07:29 UTC, ierof requested changes

2024-07-15 07:29 UTC, ierof commented on _posts/2024-07-05-versioned-entity-revision.md
> +tags: v9preview2 v9
кажется, задача войдёт уже в следующее превью

2024-07-15 07:29 UTC, ierof commented on _posts/2024-07-05-versioned-entity-revision.md
> +Теперь каждый терминал фронта ведет свою ревизию объектов. Это означает, что отказы в применении изменений устранены.
```suggestion
Теперь каждый терминал фронта ведет свою ревизию объектов. Это означает, что необоснованные отказы в применении изменений по причине "архитектурной особенности" iiko устранены. 
```

2024-07-15 07:29 UTC, ierof commented on _posts/2024-07-05-versioned-entity-revision.md
> +
Можно добавить абзац про то, что теперь ревизию нельзя использовать как критерий сравнения объектов на разных терминалах. Что терминал А не сможет узнать, актуальное ли у него состояние объекта сравнив ревизию.

2024-07-15 07:29 UTC, ierof commented on v6/ru/Data editing.md
> +- Для корректной работы синхронизации доступа к данным необходимо с помощью iikoOffice в настройках группы назначить главную кассу. Плагин, использующий функции редактирования данных, предпочтительно
Не Preview2, а та будущая версия API, в которую оно войдёт

2024-07-15 07:29 UTC, ierof commented on _posts/2024-07-05-versioned-entity-revision.md
> +В  [`SamplePlugin`](https://github.com/iiko/front.api.sdk/tree/master/sample/v9preview2/Resto.Front.Api.SamplePlugin) был добавлен [`пример`](https://github.com/iiko/front.api.sdk/blob/master/sample/
Думаю, пример будет по другой ссылке.

2024-07-19 13:47 UTC, GulnaraBikbova commented on _posts/2024-07-05-versioned-entity-revision.md
> +tags: v9preview2 v9
Верно, следует указать следующую версию

2024-10-01 13:28 UTC, ierof approved these changes

2024-10-01 13:29 UTC, merged