Дописать документацию по новым вещам в API
iiko/front.api.doc pull request #206
Opened 2024-07-15 12:56 UTC by ierof

https://jira.iiko.ru/browse/RMS-56208

2024-07-16 13:29 UTC, GulnaraBikbova requested changes

2024-07-16 13:29 UTC, GulnaraBikbova commented on _posts/2024-05-03-change-progressbar-text.md
> +В API V9Preview2 добавлена возможность менять текст на прогрессбаре при выполнении [операций внешнего фискального регистратора](https://iiko.github.io/front.api.doc/v6/ru/CashRegisters.html):
Также менять текст на прогрессбаре можно и в `IChequeTaskProcessor`.

2024-07-16 13:29 UTC, GulnaraBikbova commented on _posts/2024-04-17-template-section.md
> +Атрибут name используется определяет конкретную секцию. Также может использоваться для определения вида документа (гостевой счет, квитанция об оплате, сервисный чек и т.д.)
Атрибут `name `определяет конкретную секцию.

2024-07-16 13:29 UTC, GulnaraBikbova commented on _posts/2024-04-17-template-section.md
> +Подписка `BeforeFormatDocument` предназначена для добавления дополнительной информации в чек, которой нет в модели данных, но которая может быть модели данных плагина, либо для выполнения бизнес-логи
Первая половина предложения понятна, вторая нет.. Что-то видимо здесь пропущено: "...но которая может быть модели данных плагина..."

2024-07-16 13:29 UTC, GulnaraBikbova commented on _posts/2024-03-04-new-chequetask-props.md
> +В API V9Preview2 добавлена возможность менять задавать и использовать [`ChequeSale.FiscalTags`](https://iiko.github.io/front.api.sdk/v9/html/P_Resto_Front_Api_Data_Device_Tasks_ChequeSale_FiscalTags.
"...менять, задавать и использовать..."

А что на счет `Operations.GetDocumentFiscalTags()`, относится ли оно к этой теме?

2024-07-16 13:32 UTC, ierof commented on _posts/2024-05-03-change-progressbar-text.md
> +В API V9Preview2 добавлена возможность менять текст на прогрессбаре при выполнении [операций внешнего фискального регистратора](https://iiko.github.io/front.api.doc/v6/ru/CashRegisters.html):
Ага, увидела, что и это делалось не в рамках RMS-49136. А по замечанию о тестировании это было не сказать :)

2024-07-16 13:34 UTC, ierof commented on _posts/2024-04-17-template-section.md
> +Подписка `BeforeFormatDocument` предназначена для добавления дополнительной информации в чек, которой нет в модели данных, но которая может быть модели данных плагина, либо для выполнения бизнес-логи
Это из статьи Ренана на вики копи-паст. Поправлю

2024-07-17 09:29 UTC, ierof commented on _posts/2024-03-04-new-chequetask-props.md
> +В API V9Preview2 добавлена возможность менять задавать и использовать [`ChequeSale.FiscalTags`](https://iiko.github.io/front.api.sdk/v9/html/P_Resto_Front_Api_Data_Device_Tasks_ChequeSale_FiscalTags.
к этой теме относится, но делалось не в рамках этой задачи.

2024-07-17 09:34 UTC, ierof commented on _posts/2024-03-04-new-chequetask-props.md
> +В API V9Preview2 добавлена возможность менять задавать и использовать [`ChequeSale.FiscalTags`](https://iiko.github.io/front.api.sdk/v9/html/P_Resto_Front_Api_Data_Device_Tasks_ChequeSale_FiscalTags.
Это делалось в RMS-56411, тоже допишу это в документацию

2024-07-17 12:08 UTC, GulnaraBikbova approved these changes

2024-07-17 12:08 UTC, GulnaraBikbova commented on _posts/2024-04-17-template-section.md
> +Атрибут `name` используется определяет конкретную секцию. Также может использоваться для определения вида документа (гостевой счет, квитанция об оплате, сервисный чек и т.д.)
```suggestion
Атрибут `name` определяет конкретную секцию. Также может использоваться для определения вида документа (гостевой счет, квитанция об оплате, сервисный чек и т.д.)
```

2024-07-17 12:28 UTC, merged