Front Api: описать возможности по добавлению и проведению платежей
iiko/front.api.doc pull request #21
Opened 2019-03-18 14:35 UTC by rgalk

Задачи:
https://jira.iiko.ru/browse/RMS-48531
https://jira.iiko.ru/browse/RMS-48669

2019-04-03 17:36 UTC, vcpp requested changes

2019-04-03 17:36 UTC, vcpp commented on v6/ru/Payments.md
> +- [IEditSession.AddPreliminaryPaymentItem](https://iiko.github.io/front.api.sdk/v6/html/Overload_Resto_Front_Api_V6_Editors_IEditSession_AddPreliminaryPaymentItem.htm) &mdash; добавить предварительну
осмысленно → имеет смысл?
Или вообще убрать это слово, «только для заказов доставки».

2019-04-03 17:36 UTC, vcpp commented on v6/ru/Payments.md
> +Также можно использовать одноименные [методы](https://iiko.github.io/front.api.sdk/v6/html/Methods_T_Resto_Front_Api_V6_Extensions_OperationServiceExtensions.htm) сервиса операций&ndash;расширений, в
создаваётся → создаётся.

2019-04-03 17:36 UTC, vcpp commented on v6/ru/Payments.md
> +(_отличие в необходимости выполнения нескольких действий на заказом.
над заказом

2019-04-03 17:36 UTC, vcpp commented on v6/ru/Payments.md
> +Платеж может быть добавлен в заказ только если заказ находится в статусе новый (`New`) или пречек (`Bill`), иначе метод выбрасывает исключение [`ConstraintViolationException`](http://iiko.github.io/f
```suggestion
Платеж может быть добавлен в заказ, только если заказ находится в статусе новый (`New`) или пречек (`Bill`), иначе метод выбрасывает исключение [`ConstraintViolationException`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Exceptions_ConstraintViolationException.htm).
```

2019-04-03 17:36 UTC, vcpp commented on v6/ru/Payments.md
> +также сущестует метод, с помощью которого можно превратить элемент оплаты в предоплату iikoFront
```suggestion
также существует метод, с помощью которого можно превратить элемент оплаты в предоплату iikoFront
```

2019-04-03 17:36 UTC, vcpp commented on v6/ru/Payments.md
> +var order = PluginContext.Operations.GetOrders().Single(o => o.Id == orderId);
Для получения по id лучше использовать `TryGetOrderById`. А вообще странно, имея заказ, терять его, оставляя только id, а потом обратно добывать.

2019-04-03 17:36 UTC, vcpp commented on v6/ru/Payments.md
> + [IOperationService.PayOrderAndPayOutOnUser](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_PayOrderAndPayOutOnUser.htm) заказ закроется, распечатаются все необхо
```suggestion
 [IOperationService.PayOrderAndPayOutOnUser](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_PayOrderAndPayOutOnUser.htm) заказ закроется, распечатаются все необходимые квитанции, будет напечатан фискальный чек, а сам заказ окажется в закрытых в iikoFront (_NOTE: дополнить раздел пояснением про фискальное изъятие в расчет официанту_).
```

2019-04-03 17:36 UTC, vcpp commented on v6/ru/Payments.md
> +Возврат оплаты и возврат заказов по инициативе плагина не предусмотрен, он должен выполняться со стационарных терминалов iikoFront пользователем системы.
Правильнее сказать, что возврат пока не реализован.
Возврата заказов через плагин нет ведь не потому, что это какое-то принципиальное решение, а, как говорит старина Липперт, _because no one designed, implemented and shipped the feature to customers._
В будущем, возможно, и сделаем.

2019-04-03 17:36 UTC, vcpp commented on v6/ru/Payments.md
> +Поэтому со своей стороны не предпринимает действий по обработке и помечает данный элемент оплаты проведенным.
А предложение начинают с «поэтому»?

2019-04-03 17:36 UTC, vcpp commented on v6/ru/Payments.md
> +var paymentItems = operationService.GetPaymentsByOrder(order).Where(i => .IsExternal);
В V6 нет метода `GetPaymentsByOrder`. И в V5 тоже нет. Этот метод был только в старых версиях до V4 включительно.
Кроме того, в `Where` ошибка компиляции, пропущено имя переменной.

2019-04-03 17:36 UTC, vcpp commented on v6/ru/Payments.md
> +    operationService.DeleteExternalPaymentItem(paymentItem, order, сredentials);
Этот код не может работать больше одной итерации, ибо во второй и последующих итерациях ранее прочитанный заказ будет устаревшим, это будет приводить к `EntityModifiedException`.

2019-04-03 17:36 UTC, vcpp commented on v6/ru/Payments.md
> +- Оплата заказа, в котором достаточно внесенных денежных средств
Это не выглядит как список. Вернее, это выглядит как список из одного элемента, за которым следует обычный абзац без отступа, после которого как бы новый список, одна строка с отступом, а потом снова обычный абзац.

2019-04-04 07:04 UTC, rgalk commented on v6/ru/Payments.md
> +Поэтому со своей стороны не предпринимает действий по обработке и помечает данный элемент оплаты проведенным.
Начинают, если в контексте предыдущего предложения содержится причина того, что разъясняет предложение, содержащее "поэтому". Поэтому оставлю как есть.

2019-04-04 07:54 UTC, merged