RMS-48274 Возможность выполнить несколько операций под общей блокировкой
iiko/front.api.doc pull request #22
Opened 2019-03-19 00:55 UTC by vcpp

2019-03-19 09:31 UTC, ierof requested changes

2019-03-19 09:31 UTC, ierof commented on _posts/2018-12-20-continuous-operations.md
> +Подробнее в статье про [редактирование данных](v6/ru/Data editing.html)
Ссылка неправильно резолвится из-за относительного пути. В [твоём репо](https://vcpp.github.io) она ведет 
https://vcpp.github.io/front.api.doc/2018/12/20/v6/ru/Data%20editing.html

И мне не нравится то, что у нас получаются пробелы в адресах. Но каких-то проблем это не вызывает.

2019-03-19 09:31 UTC, ierof commented on _posts/2018-12-20-continuous-operations.md
> +---
В названии файла дата вхождения изменений в develop?
Потому что получится, что в новостях оно окажется где-то в середине.

2019-03-19 09:31 UTC, ierof commented on v6/ru/Data editing.md
> +В коде плагина нужно собрать серию операций в одну функцию или лямбду и передать её как callback в метод `ExecuteContinuousOperation`, который вызовет этот callback, передав ему вход специальный экзе
```suggestion
В коде плагина нужно собрать серию операций в одну функцию или лямбду и передать её как callback в метод `ExecuteContinuousOperation`, который вызовет этот callback, передав ему на вход специальный экземпляр сервиса `IOperationService`, предназначенный для непрерываемого выполнения операций:
```

2019-03-19 09:31 UTC, ierof commented on v6/ru/Data editing.md
> +Данные блокируются по мере необходимости, поэтому если посреди непрерываемой серии после успешного выполнения операций над одним объектом мы решим внести изменения в другой объект, мы вполне можем по
```suggestion
Данные блокируются по мере необходимости, поэтому если посреди непрерываемой серии после успешного выполнения операций над одним объектом мы решим внести изменения в другой объект, мы вполне можем получить [`EntityAlreadyInUseException`](https://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Exceptions_EntityAlreadyInUseException.htm).
```

2019-03-19 12:05 UTC, vcpp commented on _posts/2018-12-20-continuous-operations.md
> +---
Да, дата попадания изменений в общую ветку.
В идеале, заметка об этом появляется сразу же, но пока синхронно не поспеваем.

2019-03-19 12:06 UTC, vcpp commented on _posts/2018-12-20-continuous-operations.md
> +Подробнее в статье про [редактирование данных](v6/ru/Data editing.html)
Хм, с локальным jekyll правильно генерировалось. Поправлю.

2019-03-19 16:45 UTC, vcpp commented on _posts/2018-12-20-continuous-operations.md
> +Подробнее в статье про [редактирование данных](v6/ru/Data editing.html)
Поправил.

2019-03-19 17:07 UTC, vcpp commented on v6/ru/Data editing.md
> +Данные блокируются по мере необходимости, поэтому если посреди непрерываемой серии после успешного выполнения операций над одним объектом мы решим внести изменения в другой объект, мы вполне можем по
Чуть выше этот тип уже упоминался с гиперссылкой, зачем повторяться?
Предлагаю ориентироваться на рекомендации по [викификации](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Linking#MOS:REPEATLINK):
> ... as a rule of thumb editors should only link the term's first occurrence in the text of the article
> #### Duplicate and repeat links ####
> Generally, a link should appear only once in an article, but if helpful for readers, a link may be repeated in infoboxes, tables, image captions, footnotes, hatnotes, and at the first occurrence after the lead

2019-03-20 07:35 UTC, ierof approved these changes

2019-03-20 07:36 UTC, merged