RMS-48431 Front.Api.Devices: Доработка документации api
iiko/front.api.doc pull request #24
Opened 2019-04-11 09:15 UTC by GulnaraBikbova

2019-04-11 10:49 UTC, ierof requested changes

2019-04-11 10:49 UTC, ierof commented on 2019-04-10-publish-cashRegister-operations.md
> +Добавлена расширенная документация по проектированию собственных фискальных регистраторов. Добавлены примеры реализаций методов фискального регистратора, а также ответы на часто задаваемые вопросы.
```suggestion
[Добавлена расширенная документация]({{ site.baseurl }}/v6/ru/CashRegisters) по проектированию собственных фискальных регистраторов. Добавлены примеры реализаций методов фискального регистратора, а также ответы на часто задаваемые вопросы.
```

2019-04-11 10:49 UTC, ierof commented on 2019-04-10-publish-cashRegister-operations.md
> +
Хорошо бы ещё и в SDK https://github.com/iiko/front.api.sdk в раздел Samples запушить примеры для оборудования на базе V6Prview4.
Это можно (или даже нужно) оформить отдельной задачей.

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +---
Лучше писать каждое предложение с новой строки. Всё равно MD делит на абзацы то, что разделено двумя новыми строками. Но при просмотре диффов или при внесении предлагаемых правок удобнее оперировать предложениями, а не абзацами.

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +Если в списке поддерживаемых моделей фискальных регистраторов (ФР) в iiko вы не нашли нужной вам модели, вы можете написать свою поддержку интересующей вас модели ФРа. Это будет плагин, подключаемый
```suggestion
Если в списке поддерживаемых моделей фискальных регистраторов (ФР) в iiko вы не нашли нужной вам модели, вы можете написать свою поддержку интересующей вас модели ФРа. Это будет плагин, подключаемый к iikoFront — внешний ФР. Cм. [введение](Devices.html).
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +```sh
```suggestion
```cs
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +Для этого нужно реализовать интерфейс [`ICashRegisterFactory`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Devices_ICashRegisterFactory.htm) и зарегистрировать его в iikoFront:
```suggestion
Для этого нужно реализовать интерфейс [`ICashRegisterFactory`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Devices_ICashRegisterFactory.htm) и зарегистрировать его посредством вызова методов API:
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +Это нужно для того, чтобы в iikoRMS появилась ваша новая модель ФРа, которую потом можно будет добавить и подключить как ККТ к кассе.
нужно ли расшифровывать ещё и аббревиатуру ККТ ?

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +```sh
```suggestion
```cs
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +class SampleCashRegisterFactory : MarshalByRefObject, ICashRegisterFactory
можно сноску с пояснением про MBR-объекты и их Lifetime

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +```sh
```suggestion
```cs
```

2019-04-11 10:49 UTC, ierof commented on v6/ru/Devices.md
> +В Api весы представлены типом `IScale`. Как и любое устройство, весы в себе содержат идентификатор устройства и его имя. Тип `IScale` состоит из одной команды - взвесить (`MeasureWeight()`).
```suggestion
В API весы представлены типом `IScale`. Как и любое устройство, весы в себе содержат идентификатор устройства и его имя. Тип `IScale` состоит из одной команды - взвесить (`MeasureWeight()`).
```

2019-04-11 10:49 UTC, ierof commented on v6/ru/Devices.md
> +Для того чтобы начать пользоваться своей моделью весов, нужно зарегистрировать ее в списке оборудования. Чтобы зарегистрировать модель, нужно создать тип `IScaleFactory`, который будет являться предс
```suggestion
Для того чтобы начать пользоваться своей моделью весов, нужно зарегистрировать ее в списке оборудования. Для этого нужно создать класс, реализующий `IScaleFactory`, который будет являться представителем новой модели весов, и добавить эту модель весов в список оборудования с помощью `RegisterScaleFactory()`. 
```

2019-04-11 10:49 UTC, ierof commented on v6/ru/Devices.md
> +В `IScaleFactory` указывается имя модели оборудования и его настройки. Т.о. в BackOffice по имени модели можно будет найти весы и создать или отредактировать их настройки.
```suggestion
В `IScaleFactory` указывается имя модели оборудования и его настройки. Таким образом, в iikoOffice по имени модели можно будет найти весы и создать или отредактировать их настройки. 
```

2019-04-11 10:49 UTC, ierof commented on 2019-04-10-publish-cashRegister-operations.md
> +---
Общее замечание : сделали криво, картинки залились в корень, а не в подпапку в img

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +```sh
```suggestion
```cs
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +- [`CashRegisterSettings.OfdProtocolVersion`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Settings_CashRegisterSettings_OfdProtocolVersion.htm) - версия протакола ФФД
```suggestion
- [`CashRegisterSettings.OfdProtocolVersion`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Settings_CashRegisterSettings_OfdProtocolVersion.htm) — версия протокола формата фискальных данных, далее ФФД (вкладка *«Основные настройки»*). Актуально только для РФ.
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +- [`CashRegisterSettings.Font0Width`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Settings_CashRegisterSettings_Font0Width.htm) - ширина чековой ленты (вкладка *"Осно
```suggestion
- [`CashRegisterSettings.Font0Width`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Settings_CashRegisterSettings_Font0Width.htm) — ширина чековой ленты (вкладка *«Основные настройки»*)
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +- [`CashRegisterSettings.FiscalRegisterTaxItems`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Settings_CashRegisterSettings_FiscalRegisterTaxItems.htm) - список регис
```suggestion
- [`CashRegisterSettings.FiscalRegisterTaxItems`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Settings_CashRegisterSettings_FiscalRegisterTaxItems.htm) — список регистров ФРа, соответствующие налоговым категориям (вкладка *«Налоговые категории»*)
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +- [`CashRegisterSettings.FiscalRegisterTaxItems`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Settings_CashRegisterSettings_FiscalRegisterPaymentItem.htm) - список ре
```suggestion
- [`CashRegisterSettings.FiscalRegisterTaxItems`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Settings_CashRegisterSettings_FiscalRegisterPaymentItem.htm) — список регистров ФРа, соответствующие типам оплат (вкладка *«Типы оплат и регистры»*)
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +```sh
```suggestion
```cs
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +**1.** [`Setup()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_IDevice_Setup.htm) - установка настроек, конфигураций ФРа.
```suggestion
**1.** [`Setup()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_IDevice_Setup.htm) — установка настроек, конфигураций ФРа. 
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +```sh
```suggestion
```cs
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +**2.** [`Start()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_IDevice_Start.htm) - запуск ФРа.
```suggestion
**2.** [`Start()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_IDevice_Start.htm) — запуск ФРа.
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +По нажатию "Завершить" в окне добавления ФРа (*iikoOffice => "Настройки оборудования"*), будет вызван метод [`ICashRegisterFactory.Create()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front
Лучше кавычки-«ёлочки» везде. 
Как и длинное тире — везде вместо минуса -

```suggestion
По нажатию "Завершить" в окне добавления ФРа (*iikoOffice => «Настройки оборудования»*), будет вызван метод [`ICashRegisterFactory.Create()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_ICashRegisterFactory_Create.htm), который добавит новый ФР в список оборудования. После этого iikoRMS сможет общаться с внешним ФРом, отправлять ему команды и принимать его ответы.
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +Все настройки из коллекции [`DeviceSettings.Settings`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Device_Settings_DeviceSettings.htm) при подключении ФРа попадают на вкладк
```suggestion
Все настройки из коллекции [`DeviceSettings.Settings`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Device_Settings_DeviceSettings.htm) при подключении ФРа попадают на вкладку *«Дополнительные настройки»*:
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +Команда вызывается по нажатию "Запустить" в BackOffice. Также ФР может быть запущен автоматически, если при добавлении устройства в настройках ФР установить флаг "Запускать автоматически".
```suggestion
Команда вызывается по нажатию «Запустить» в iikoOffice. Также ФР может быть запущен автоматически, если при добавлении устройства в настройках ФР установить флаг «Запускать автоматически».
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +```sh
```suggestion
```cs
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +**3.** [`Stop()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_IDevice_Stop.htm) - остановка ФРа.
```suggestion
**3.** [`Stop()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_IDevice_Stop.htm) — остановка ФРа.
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +Команда вызывается по нажатию "Остановить" в BackOffice. Команда предназначена для остановки устройства, освобождения ресурсов и закрытия портов, например:
```suggestion
Команда вызывается по нажатию «Остановить» в iikoOffice. Команда предназначена для остановки устройства, освобождения ресурсов и закрытия портов, например:
```

2019-04-11 10:49 UTC, ierof commented on CashRegisters.md
> +```sh
```suggestion
```cs
```

2019-04-23 04:42 UTC, rengal commented on CashRegisters.md
> +- [`CashRegisterSettings.OfdProtocolVersion`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Settings_CashRegisterSettings_OfdProtocolVersion.htm) - версия протакола ФФД
Нужно указать, что версия ФФД это региональная настройка, актуальна только для российских ККТ, для всех остальных должна быть пустая строка.

2019-04-23 04:49 UTC, rengal commented on CashRegisters.md
> +Актуально для тех ФРов, драйверы которых имеют команду *"Открыть смену"*. Например, ФРы ФЗ-54, т.к. нужно указывать имя кассира.
Если ФР не имеет отдельной команды для открытия смены, то нужно вернуть успешный ответ (success-true) без выполнения операции в ФР.

2019-04-23 04:52 UTC, rengal commented on CashRegisters.md
> +- [`IsCancellation`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Tasks_BillTask_IsCancellation.htm) - аннулирование чека (актуально для Республики Белорусь и Латвии)
Беларусь

2019-04-23 04:53 UTC, rengal commented on CashRegisters.md
> +**7.** [`DoXReport()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_ICashRegister_DoXReport.htm) - печать X-отчета.
печать Х-отчета или его аналога (промежуточный суточный отчет без закрытия смены)

2019-04-23 04:54 UTC, rengal commented on CashRegisters.md
> +Чаще всего это набор информации по блюдам заказа, иногда позиции группируются по НДС. Это зависит в частности от ФР, поддерживает ли он ОФД выше 1.0
ФФД

2019-04-23 04:55 UTC, rengal commented on CashRegisters.md
> +- [`СancellingSaleNumber`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Tasks_BillTask_СancellingSaleNumber.htm) - номер сторнируемого заказа (заполняется при сторниро
(актуально только для Республики Беларусь)

2019-04-23 04:55 UTC, rengal commented on CashRegisters.md
> +- [`DiscountPercent`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Tasks_BillTask_DiscountPercent.htm) - процент скидки заказа
процент скидки на сумму заказа

2019-04-23 04:56 UTC, rengal commented on CashRegisters.md
> +- [`ResultSum`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Tasks_BillTask_ResultSum.htm) - итоговая сумма заказа
итоговая сумму заказа с учетом всех скидок и надбавок.
Правда, тут нужно уточнить - это сумма стоимости всех блюд или сумма всех оплат. Они могут быт не равны друг другу, т.к. ФФД разрешает округление (можно платить меньше до 99 коп)

2019-04-23 05:00 UTC, rengal commented on CashRegisters.md
> +- [`Code`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Tasks_ChequeSale_Code.htm) - артикул позиции
В некоторых случаях артикул может отсутствовать (в этом случае передается ноль). Например, печатается чек со сгруппированными по НДС позициям или чек предоплаты.

2019-04-23 05:01 UTC, rengal commented on CashRegisters.md
> +- [`Price`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Tasks_ChequeSale_Price.htm) - стоимость позиции
цена позиции без учета скидок и надбавок

2019-04-23 05:02 UTC, rengal commented on CashRegisters.md
> +- [`Sum`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Tasks_ChequeSale_Sum.htm) - сумма позиции, включая скидки и надбавки
итоговая стоимость позиции, учитывающая скидки и надбавки как на отдельную позицию, так и на весь чек.

2019-04-23 05:04 UTC, rengal commented on CashRegisters.md
> +- [`TaxId`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Tasks_ChequeSale_TaxId.htm) - идентификатор налоговой ставки в ФР, соответствующая той налоговой категории, ко
Если пользователь настроил сопоставление налоговых категорий iiko и ФР, то передается идентификатор налоговой ставки, которую указал пользователь. Если сопоставление не настроено (стоит значение "По умолчанию"), то передается пустая строка.

2019-04-23 05:05 UTC, rengal commented on CashRegisters.md
> +- [`TransferType`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Tasks_ChequeSale_TransferType.htm) - признак способа расчета (аванс (*"Advance"*), оплата (*"FullPaymen
Это региональная фича. Надо как-то их пометить отдельно.

2019-04-23 05:05 UTC, rengal commented on CashRegisters.md
> +После нажатия на "Пречек" на экране заказа, фронт отправляет команду ФРу и ожидает от него ответ [`CashRegisterResult`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Device_Re
состоит

2019-04-23 05:07 UTC, rengal commented on CashRegisters.md
> +- [`CashSum`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Results_CashRegisterResult_CashSum.htm) - сумма наличности в кассе за текущую КС
Сумма наличности в кассе на момент запроса

2019-04-23 05:09 UTC, rengal commented on CashRegisters.md
> +- [`TotalIncomeSum`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Results_CashRegisterResult_TotalIncomeSum.htm) - сумма выручки (наличность + безналичность) в кассе з
Это не нарастающий итог, т.к. сумма выручки может уменьшаться при возврате. Лучше написать так:
сумма выручки = сумме продаж - сумма возвратов за смену. 
Непосредственно после закрытия смены или открытия смены сумма выручки должна быть равна нулю.

2019-04-23 05:11 UTC, rengal commented on CashRegisters.md
> +- [`DocumentNumber`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Results_CashRegisterResult_DocumentNumber.htm) - номер документа (для ФЗ-54: номер фискального докуме
если говорить про ФЗ-54, то в нем нет таких документов, как "внесение" и "изъятие"

2019-04-23 05:12 UTC, rengal commented on CashRegisters.md
> +- [`SaleNumber`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Results_CashRegisterResult_SaleNumber.htm) - номер чека (чек: чек продажи, чек покупки)
чеков покупки у нас нет.

2019-04-23 05:13 UTC, rengal commented on CashRegisters.md
> +- [`CashPayment`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Tasks_ChequeSale_CashPayment.htm) - сумма оплаты наличностью
сумма оплаты наличными

2019-04-23 05:13 UTC, rengal commented on CashRegisters.md
> +Команда вызывается при закрытии заказа (по нажатию "Оплатить" на экране кассы) в iikoFront. Вся необходимая информация по заказу, его оплатах, кассире приходит в аргементе [`ChequeTask`](http://iiko.
аргументе

2019-04-23 05:15 UTC, rengal commented on CashRegisters.md
> +Если отрицательный ответ iikoFront обрабатывает одинаково, то успешный результат для каждой операции анализируется по-разному.
даже если success=false, у нас ведь есть механизм проверки на задвоение. Поэтому нельзя говорить, что "если результат вернулся неуспешным, то iikoFront будет считать, что на ФР команда не была выполнена"

2019-04-23 05:17 UTC, rengal commented on CashRegisters.md
> +- [`CreditSum`](http://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_V6_Data_Device_Tasks_ChequeSale_CreditSum.htm) - сумма по чеку постоплатой (в кредит)
CreditSum, PrepaymentSum, ConsiderationSum - региональные фичи

2019-04-23 05:21 UTC, rengal commented on CashRegisters.md
> +При проведении оплат, предоплат, возвратов, внесений, изъятий iikoFront может сверять свои подсчеты денежных сумм по кассовой смене с подсчетами ФРа, это зависит от конфигурации iikoFront, по-умолчан
Делается это для того, чтобы избежать возможного дублирования печати чека, который мог все-таки напечататься, даже если вернулся неуспешный результат (success=false)

Про ошибку в памяти ФР писать не надо, это частный случай всего возможного спектра ошибок (и довольно редкий случай, причем именно при этой ошибке защита от задвоения не сработает, ведь в памяти ФР мусор, и cashSum, totalIncomeSum ненадежны)

2019-04-23 05:23 UTC, rengal commented on CashRegisters.md
> +**13.** [`IsDrawerOpened()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_ICashRegister_IsDrawerOpened.htm) - открыт ли денежный ящик.
если ФР не поддерживает команду получения статуса денежного ящика, то нужно вернуть success=true, opened=false) - или как? требуется комментарий фронтовика

2019-04-23 05:24 UTC, rengal commented on CashRegisters.md
> +**17.** [`DoCorrection()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_ICashRegister_DoCorrection.htm) - печать чека коррекции (*iikoFront => "Доп" => "Чек коррекции"*).
региональная фича

2019-04-23 05:25 UTC, rengal commented on CashRegisters.md
> +        // команда приветсвия пользователя с кодовым именем "HelloWorld"
приветствия

2019-04-23 13:52 UTC, rengal commented on CashRegisters.md
> +Чаще всего это набор информации по блюдам заказа, иногда позиции группируются по НДС. Это зависит в частности от ФР, поддерживает ли он ОФД выше 1.0
`        public CashRegisterResult DoCheque([NotNull] ChequeTask chequeTask)
        {
            if (chequeTask == null)
                throw new ArgumentNullException(nameof(chequeTask));

            if (chequeTask.IsCancellation)
            {
                throw new DeviceException("Чек аннулирования не поддерживается");
            }

            driver.SetCashier(chequeTask.CashierName, chequeTask.CashierTaxpayerId);

            //Отменяем открытие документы, если они есть
			driver.ResetDevice();
			
			//Открыть чек
            if (chequeTask.isRefund)
                driver.OpenRefundCheck();
            else
                driver.OpenSaleCheck()

			//печатаем номер стола и заказа
            driver.PrintText(string.IsNullOrWhiteSpace(chequeTask.TableNumberLocalized)
                ? string.Format("Стол: {0}, Заказ № {1}", chequeTask.TableNumber, chequeTask.OrderNumber)
                : chequeTask.TableNumberLocalized);

            //Печатаем дополнительные строки в начале чека
            if (!string.IsNullOrWhiteSpace(chequeTask.TextBeforeCheque))
                driver.PrintText(chequeTask.TextBeforeCheque);

            foreach (var sale in chequeTask.Sales)
            {
                var taxId = GetTaxId(sale); //получаем налоговую ставку
                driver.RegisterItem(sale.Name, sale.Price, sale.Amount, taxId);

                //Регистрируем скидку на позицию
				if (sale.DiscountSum > 0.0m)
                    driver.RegisterDiscount(sale.DiscountSum)
				
				//Регистрируем надбавку на позицию
                if (sale.IncreaseSum > 0.0m)
                    driver.RegisterIncrease(sale.IncreaseSum);
            }
			
			//Печатает подытог чека
			driver.PrintSubtotal();
			
			//Регистрируем скидку на подытог чека
			if (chequeTask.DiscountSum > 0.0m)
                driver.RegisterSubtotalDiscount(chequeTask.DiscountSum)

			//Регистрируем надбавку на подытог чека
            if (chequeTask.IncreaseSum > 0.0m)
				driver.RegisterSubtotalIncrease(chequeTask.IncreaseSum);

            foreach (var cardPayment in chequeTask.CardPayments)
            {
				var paymentRegisterId = GetPaymentRegisterId(cardPayment); //получить номер типа оплаты
                driver.AddPayment(GetCardPaymentId(cardPayment), cardPayment.Sum);
            }

			cardPayments = chequeTask.CardPayments.Sum(cardPament=>cardPayment.Sum);
			
            if (chequeTask.CashPayment > 0.0m || cardPayments == 0.0m)
            {
			    //cashPaymentId - номер типа оплаты для наличных
                driver.AddPayment(cashPaymentId, cardPayment.Sum);
            }

			//Печатаем дополнительные строки в конце чека
            if (!string.IsNullOrWhiteSpace(chequeTask.TextAfterCheque))
                driver.PrintText(chequeTask.TextAfterCheque);

            //Закрываем чек
			driver.CloseCheck();
            return GetCashRegisterData();
        }`

2019-04-23 13:59 UTC, rengal commented
`public CashRegisterResult GetCashRegisterData()
{            
    CheckState(State.Running);
    var totalIncomeSum = driver.GetSalesSum() - driver.GetRefundsSum();
    var cashSum = driver.GetCashSum();
    var serialNumber = driver.GetSerialNumber();
    var sessionNumber = driver.GetSessionNumber();
    var dateTime = driver.GetDateTime();
    var receiptNumber = driver.GetLastReceiptNumber();
    var documentNumber = driver.GetLastDocumentNumber();

    return new CashRegisterResult(cashSum, totalIncomeSum, sessionNumber, serialNumber, receiptNumber,
        documentNumber, null, dateTime.ToString(CultureInfo.InvariantCulture));
}`

2019-04-24 10:01 UTC, GulnaraBikbova commented on CashRegisters.md
> +**13.** [`IsDrawerOpened()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Devices_ICashRegister_IsDrawerOpened.htm) - открыт ли денежный ящик.
просто true.
bool IsDrawerOpened();

2019-04-24 10:21 UTC, GulnaraBikbova commented on 2019-04-10-publish-cashRegister-operations.md
> +
Примеры если добавлять, то в закомментированном виде, так как используют выдуманный driver, который всегда есть в реальном ФР.

2019-05-21 14:54 UTC, ierof commented
Уже залито в https://github.com/iiko/front.api.doc/pull/35

2019-05-21 14:54 UTC, closed without merging