RMS-48891 Front.Api.Documentation: Сделать документацию о добавлении …
iiko/front.api.doc pull request #36
Opened 2019-05-21 15:53 UTC by GulnaraBikbova

…обработчиков на экран закрытого заказа

2019-05-21 17:53 UTC, ierof approved these changes

2019-05-21 17:53 UTC, merged

2019-05-21 18:36 UTC, vcpp requested changes

2019-05-21 18:36 UTC, vcpp commented on _posts/2019-03-13-add-action-for-closed-order.md
> +В API V6 добавлен метод [`AddButtonOnClosedOrderView()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Extensions_PluginIntegrationServiceExtensions_AddButtonOnClosedOrderView.htm)
Битая ссылка на ActionOnClosedOrderView.html.
Посмотри, как в других местах сделаны ссылки через site.baseurl.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +﻿---
Надо убрать byte order mark в начале файла, иначе jekyll не будет генерить html для этого файла.
Из [спеки](https://jekyllrb.com/docs/front-matter/):
> UTF-8 Character Encoding Warning
If you use UTF-8 encoding, make sure that no BOM header characters exist in your files or very, very bad things will happen to Jekyll. This is especially relevant if you’re running Jekyll on Windows.

Везде используем UTF8 without BOM.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +title: Расширение функционала экрана закрытого заказа
Может, просто «Экран закрытого заказа»? Длинный заголовок некрасиво выглядит в левом блоке меню, занимая две строки.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +Для примера, с помощью SDK SamplePlugin была добавлена кнопка с надписью *«SamplePlugin: Show OK popup»*.
```suggestion
Например, вот так выглядит кнопка *«SamplePlugin: Show OK popup»*, добавляемая плагином SamplePlugin из SDK. 
```

Второе предложение не сообщает ничего нового, можно убрать.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +По нажатию на кнопку *«SamplePlugin: Show OK popup»*, описанное плагином действие выполняется.
Надо ли уточнять, что обработчик кнопки вызывается по клику на ней? По-моему, это очевидно.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +Допустим плагин просто инициирует показ окна с сообщением на UI iikoFront.
Допустим — вводное слово, нужна запятая.
*Просто* — слово-паразит, в данном контексте нет сопоставления просто/сложно. Это имело бы смысл в сравнении вида «раньше для достижения цели проделывали то-то и то-то, а теперь *просто* дёргаем готовую функцию».
*Плагин инициирует показ* — давай говорить проще: *плагин показывает* :-)
*Показ окна с сообщением* — здесь можно дать перекрёстную ссылочку на соответствующую статью.
*Показ окна на UI* — масло масленое, можно было не уточнять про UI.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +Плагин может добавить сразу несколько действий на экран закрытого заказа.
В начале статьи мы говорили, что на экран можно добавить свои _команды_ (которые выполнят _операции_), а теперь мы говорим о добавлении _действий_ имея в виду то же, что и _команды_ (_операции_). Уже в следующей строке речь идёт о добавлении _кнопок_. Чуть ниже о добавлении _расширений_. Информацию легче усвоить. если одну и ту же вещь мы везде называем одним термином. Зоопарк синонимов нежелателен.

Надо стараться придерживаться единой фразеологии, включая термины.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +## Введение
Может, ну его, этот подзаголовок?

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +Например, с помощью SDK SamplePlugin были добавлены 2 кнопки: *«SamplePlugin: Show OK popup»* и *«SamplePlugin: Show OK popup»*.
Судя по картинке, в первый раз “OK popup”, а во второй раз “input popup”.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +Например, с помощью SDK SamplePlugin были добавлены 2 кнопки: *«SamplePlugin: Show OK popup»* и *«SamplePlugin: Show OK popup»*.
Кстати, я, конечно, понимаю, что картинки уже неохота будет переделывать, но зачем в тексте кнопки писать название плагина? Мы его везде пишем, отчего может сложиться мнение, что это рекомендуемый шаблон, и с нас будут брать пример. Пользователь-то не видит границы между штатной функциональностью и расширениями, у него единый UI, и пусть бы кнопки там напрямую отражали доступные действия, без уточнения, что кнопка плагинная. Так и короче было бы.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +По нажатию на *«Дополнения»* будет выведен список всех расширений, добавленные плагинами.
```suggestion
По нажатию на *«Дополнения»* будет выведен список всех расширений, добавленных плагинами. 
```

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +Тогда на экране закрытого заказа появится кнопка *«Дополнения»*.
Здесь логика неточна: кнопка «Дополнения» появится не только при добавлении плагином двух и более действий, но также при добавлении другими плагинами своих действий. Кнопка нашего плагина, даже если она у нас одна-единственная, схлопнется в «Дополнения» при наличии кнопок от других плагинов.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +![ButtonOnPastOrderView](../../img/actionOnClosedOrderView/buttonOnPastOrderView.png)
Странный диалог получился — список «Дополнительные операции» с элементами «Тип заказа» и «Отделение», которые нисколько не операции. И плохо, что у кнопки другой текст («Дополнительно» вместо «Дополнения») и другая иконка. Но к документации по API это уже не относится.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +Плагин может добавить сразу несколько действий на экран закрытого заказа.
Если метод называется `AddButtonOn...View`, то давай везде называть это кнопкой.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +- **string** — название кнопки, отображается на UI.
Названия типов лучше обернуть в гравис (\`string\`), чтобы получить моноширинный шрифт: `string`.
Выделять слова жирным лишний раз не стоит.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +Функция регистрации операции на экран закрытого заказа **текущей** кассовой смены [`AddButtonOnClosedOrderView()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Extensions_PluginIn
Нужно оставить пустую строку перед списком, потому что в md одиночные переносы строки просто удаляются. Сейчас список вытянулся в строку и выглядит некрасиво.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +- **action<IOrder, ICashRegisterInfo, IViewManager** — функция, которая принимает на вход заказ [`IOrder`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Orders_IOrder.htm), фи
«Action», не «action». Поскольку мы используем регистрозависимый C#, необходимо сохранять точный регистр в именах типов.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +- **action<IOrder, ICashRegisterInfo, IViewManager** — функция, которая принимает на вход заказ [`IOrder`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_Data_Orders_IOrder.htm), фи
Ацент смещён на аргументы функции, хотя они очевидны из сигнатуры и не нуждаются в пояснениях.
Вместо «функция, которая принимает на вход ...» следовало сказать «функция, которая будет вызвана при нажатии на кнопку».

А вообще я не вижу смысла подробно расписывать здесь сигнатуру методов и назначение аргументов, для этого есть автогенерируемая xml-документация. Здесь лучше иметь высокоуровневый обзор функциональности, опирающийся на типы и функции в коде. Тебе «повезло», что у тебя всего две функции, но в общем случае их может быть много, и их детальное описание лишь разбавит статью водой.

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +Заказы закрытых кассовых смен iikoFront не хранит у себя в хранилище, поэтому в методе [`AddButtonOnPastOrderView()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_Extensions_Plugi
«Не хранит в хранилище» = «не хранит», не надо усложнять :-)

2019-05-21 18:36 UTC, vcpp commented on v6/ru/ActionOnClosedOrderView.md
> +Примеры реализации можно посмотреть в проекте SDK SamplePlugin.
В SamplePlugin'е море примеров, желательно указать конкретный класс.

2019-05-22 08:34 UTC, GulnaraBikbova commented on v6/ru/ActionOnClosedOrderView.md
> +Например, с помощью SDK SamplePlugin были добавлены 2 кнопки: *«SamplePlugin: Show OK popup»* и *«SamplePlugin: Show OK popup»*.
>>но зачем в тексте кнопки писать название плагина?
Да, мы его везде пишем, больше для наглядности, чтобы различать, где фронтовые кнопки, а где плагинные.
Думаю разработчик укажет нужное ему имя кнопки.