RMS-47606 Front.Api: Написать статью о функциях ввода данных.
iiko/front.api.doc pull request #4
Opened 2018-11-26 12:58 UTC by ierof

https://github.com/ierof/front.api.doc/blob/RMS-47606.IViewManager/v6/ru/ViewManager.md

2018-11-28 21:33 UTC, vcpp requested changes

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +[`IViewManager`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_UI_IViewManager.htm "IViewManager") это интерфейс, позволяющий показывать предопределенный набор окон iikoFront польз
* Когда подлежащее и сказуемое представлены одной частью речи, необходимо тире (IViewManager — это интерфейс).
* Причастный оборот «реализующий данный интерфейс» расположен после определяемого слова «объект», поэтому должен обособиться запятыми. А вообще, учитывая, что в Api почти все типы представлены интерфейсами, предлагаю не уделять много внимания различию между интерфейсом и реализующим его классом.
* Может, заменим «окна» на «диалоговые окна»? Это избавит от необходимости уточнения, что окно показывается пользователю, и что там есть возможность ввода данных, определение диалоговых окон (dialog boxes) широко известно.
* Про последствия использования объекта после уничтожения (`ObjectDisposedException`), на мой взгляд, избыточно говорить, достаточно обозначить время жизни объекта.
```suggestion
[`IViewManager`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_UI_IViewManager.htm "IViewManager") позволяет показывать предопределённый набор встроенных в iikoFront диалоговых окон. Эта возможность доступна плагину, когда iikoFront в рамках модальной операции передаёт ему управление, вызывая соответствующий метод и передавая в него одним из аргументов экземпляр `IViewManager`. Данный объект актуален только в рамках метода, в который он приходит, и будет уничтожен, когда плагин вернёт управление из этого метода. 
```

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Места, где управление передается от iikoFront в плагин:
Ой, я, ещё не дочитав до этого места, назвал сие «модальными операциями». На мой взгляд, это точнее отражает суть, ведь важна именно UI-составляющая, что фронт выполняет модальную (поверх всего на UI) операцию. Так-то в фоне управление много где передаётся, и синхронно (вставки в пречек, например), и асинхронно (уведомления об изменении справочников).

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +- Встраивание кнопки в меню "Дополнения" (см. [`IPluginIntegrationService.AddButton()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IPluginIntegrationService_AddButton.htm "IPlug
Кстати, я до этого писал «ёлочки». Не хочу навязывать свой стиль. Стоит ли заморачиваться с выработкой единого стиля или будем считать допустимым разные подходы? Это касается не только кавычек, но и тире (часто вместо него пишут дефис), буквы «ё» и прочего занудства.
Предлагаю пока не обращать на это внимание, дабы не отпугнуть авторов контента, а если у меня случится приступ перфекционизма, я причешу. Идёт? :-)

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Вы вызываете метод `var result = viewManager.ShowSomeThing(...)` и обрабатываете результат. В зависимости от сигнатуры конкретного метода в результате вы получаете либо переменную примитивного типа (
Может, без мы/вы? Например, «Плагин вызывает метод ...».

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Если вам нужно показать уведомительное сообщение пользователю, то рекомендуется использовать [`OperationService.AddNotificationMessage()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Ap
Давай сообщения в левом верхнем углу называть немодальными.
Уведомления/предупреждения/ошибки — это уже дальнейшее разделение немодальных сообщений (notification/warning/error).

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Если вам нужно показать уведомительное сообщение пользователю, то рекомендуется использовать [`OperationService.AddNotificationMessage()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Ap
Предлагаю такую терминологию: iiko — компания, iikoFront — приложение (это к “api iiko”).

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Если вам нужно показать уведомительное сообщение пользователю, то рекомендуется использовать [`OperationService.AddNotificationMessage()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Ap
Не понял, о какой намеренно непредоставляемой возможности здесь идёт речь.
И ещё запятой не хватает перед «нажать».

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +`ShowYesNoPopup()` показывает окно с вашим текстом и двумя кнопками и возвращает `true` если нажали на «Да».
Запятая перед «если».
Предлог «на», кажется, можно опустить, оставив _..., если нажали «Да»_.

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +`ShowChooserPopup()` в качестве параметров принимает список строк и опционально индекс выбранного по умолчанию элемента, а возвращает индекс выбранного элемента. Имеет extention, который принимает сп
Раз тут дважды (на входе и выходе) «выбранный элемент», и это разные элементы, хорошо бы оба использования сделать ясными. В первом случае уже «выбранный _по умолчанию_ элемент». Во втором предлагаю «выбранный _пользователем_ элемент».

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +- нужно ли превращать первые буквы каждого вводимого слова в заглавные *(удобно для ввода имём собственных)*
```suggestion
- нужно ли превращать первые буквы каждого вводимого слова в заглавные *(удобно для ввода имён собственных)*
```

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Кроме упомянутого выше метода, есть `ShowExtendedInputDialog()`. Одним из его параметров является класс настроек `ExtendedInputDialogSettings`. Если в нём задать `ExtendedInputSettings.EnableNumericS
`ExtendedInputSettings` был до V5 включительно, с V6 идёт `ExtendedInputDialogSettings`. Тут они вперемешку.

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +### Диалог ввода числовых строк
Лишняя запятая между «настройкой, можно».

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +### Диалог ввода числовых строк
Вероятно, имелось в виде «_В_ отличие от ..., тут данные представляют собой строку».

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Кроме упомянутого выше метода, есть `ShowExtendedInputDialog()`. Одним из его параметров является класс настроек `ExtendedInputDialogSettings`. Если в нём задать `ExtendedInputSettings.EnableNumericS
Вроде бы более правильный термин «ведущие нули», а лидируют они в виде кальки с английского.
Кстати, помимо нулей слева появляется возможность вводить длинные числа (больше, чем `int`).

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +    TabTitleNumericString = "Ваш поясняющий текст числам"
Может, без «ваш»? Или вообще «заголовок вкладки для ввода числа», а то я смысл слов «поясняющий текст числам» понял лишь после прочтения имени свойства :-)

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +// analize result
```suggestion
// analyze result
```

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Ещё одна опция у настроек для `ShowExtendedInputDialog()` это `ExtendedInputSettings.EnableBarcode = true`, которая идёт совместно с `ExtendedInputSettings.TabTitleBarcode`. Фактически не нужен. Возм
Несогласованно вышло: «Ещё одна опция ..., которая идёт ... Фактически не нужен.», «...будет реализована и сканирование».

Не понял, почему ввод штрихкодов «фактически не нужен» и зачем рассказывать про клиента, которому он всё-таки нужен. И про баг RMS-48214, наверное, нет смысла писать, это же просто лишний клик для пользователя, с точки зрения плагина разницы нет — он показал диалог и получил результат.

```suggestion
Ещё одна опция у настроек для `ShowExtendedInputDialog()` — это `ExtendedInputDialogSettings.EnableBarcode = true`, которая идёт совместно с `ExtendedInputDialogSettings.TabTitleBarcode`. Чтобы интерпретировать результат ввода, нужно привести возвращаемый `IInputDialogResult` к `BarcodeInputDialogResult`.
```

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Ещё одна опция у настроек для `ShowExtendedInputDialog()` это `ExtendedInputSettings.EnablePhone = true`, которая идёт совместно с `ExtendedInputSettings.TabTitlePhone`. В этом случае валидация вводи
```suggestion
Ещё одна опция у настроек для `ShowExtendedInputDialog()` это `ExtendedInputDialogSettings.EnablePhone = true`, которая идёт совместно с `ExtendedInputDialogSettings.TabTitlePhone`. В этом случае валидация вводимых пользователем данных будет происходить в соответствии с настройками в системе для телефонных номеров, в поле ввода будет маска с кодом страны и данные не будут считаться валидными, пока не будет нужное количество символов. А пока введенные данные не будут валидными, нажать «OK» будет невозможно. Чтобы интерпретировать результат ввода, нужно привести возвращаемый `IInputDialogResult` к `PhoneInputDialogResult`.
```

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Прокатку карт можно включить и в `ShowInputDialog()` и в `ShowExtendedInputDialog()`. В первом случае нужно указать
```suggestion
Прокатку карт можно включить и в `ShowInputDialog()`, и в `ShowExtendedInputDialog()`. В первом случае нужно указать 
```

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +`type = InputTypes.Card`, во втором – `ExtendedInputSettings.EnableCardSlider = true`. В обоих случаях чтобы интерпретировать результат ввода, нужно привести возвращаемый `IInputDialogResult` к `Card
```suggestion
`type = InputTypes.Card`, во втором – `ExtendedInputDialogSettings.EnableCardSlider = true`. В обоих случаях, чтобы интерпретировать результат ввода, нужно привести возвращаемый `IInputDialogResult` к `CardInputDialogResult`.
```

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +### Note
Мы на каком языке пишем? :-)

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Способы ввода в `ShowInputDialog()` и `ShowExtendedInputDialog()` можно комбинировать путём сочетания доступных настроек. Например, можно одновременно просить пользователя ввести номер и прокатать ка
```suggestion
Способы ввода в `ShowInputDialog()` и `ShowExtendedInputDialog()` можно комбинировать путём сочетания доступных настроек. Например, можно просить пользователя ввести номер или прокатать карту. В этом случае возвращаемый результат нужно будет пытаться приводить к каждому из ожидаемых типов результатов. 
```

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +    TabTitleBarcode = "Ваш поясняющий текст штрихкодам",
Ваш, ваш... у нас же не принято так часто выкать :-)
Я бы предложил «Заголовок вкладки штрихкодов».

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Т.к. ваши плагины написаны на .net, вы вольны использовать любые средства, в том числе вы вправе показывать собственные окна. Теоретически, показывать свои окна вы можете в любой момент. Есть пара мо
Очень много «вы». Непонятно, как возможность показывать окна связана с .Net.

```suggestion
Если перечисленных диалоговых окон недостаточно, плагин может показывать собственные окна, однако, необходимо учитывать некоторые нюансы.
```

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Во-первых, по умолчанию в процессе плагина нет STA-потока. Вам нужно его явно инициализировать. Пример кода:
Тут хорошо бы дать ссылочку на https://msdn.microsoft.com/library/ms809971.aspx.

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +Во-вторых, т.к. планиг это отдельный процесс, по умолчанию показанное из плагина окно не приобретает фокус. Фокус окну может дать только пользователь. Есть разные способы решить задачу форсированного
Противоречие между утверждением, что фокус дать может только пользователь и примером, как это сделать без пользователя. Предлагаю вообще не говорить про пользователя, раз такое дело.

Проблема с фокусом уходит на второй план, если окно плагина окажется под фронтовым окном. Установка поверх всех окон не спасёт от проваливания под другие topmost-окна и не защитит от кликов по видимым областям нижележащих окон.
Клик по координатам может попасть не в то окно или выполнить нежелательное действие, так себе идея.
Я присматривался к варианту [сделать](https://stackoverflow.com/questions/10676649/attach-window-to-window-of-another-process) окно плагина дочерним по отношению к фронтовому через SetParent, но для него нужно раздобыть hwnd окна фронта. Мы даже уже делали это для одного из наших плагинов, но hwnd добывали силами плагина. Возможно, стоит опубликовать в IViewManager.

2018-11-28 21:33 UTC, vcpp commented on v6/ru/ViewManager.md
> +
Тут можно добавить ещё нюансов про foreground/topmost, про стили, про конфигурации с несколькими экранами, где окно фронта может быть открыто на одном из экранов (на втором — экран покупателя) или растянуто на все экраны (например, сборный экран на кухне).

2018-11-30 14:19 UTC, ierof commented on v6/ru/ViewManager.md
> +Если вам нужно показать уведомительное сообщение пользователю, то рекомендуется использовать [`OperationService.AddNotificationMessage()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Ap
Можно я добавлю техническое определение "немодальный", но оставлю бытовое пояснение про "левый верхний угол"?

2018-11-30 14:22 UTC, ierof commented on v6/ru/ViewManager.md
> +Если вам нужно показать уведомительное сообщение пользователю, то рекомендуется использовать [`OperationService.AddNotificationMessage()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Ap
Ко мне обращались с вопросом  "Показать показать сообщение с одной кнопкой ОК?"
Мы тогда с тобой совещались и решили, что не нужно в api-шный `IViewManager` добавлять такую возможность, т.к. незачем в этом случае провоцировать ожидание, пока окно закроют. А для цели "проинформировать" подойдут messeges.

Вот по это данный абзац.

2018-11-30 14:28 UTC, ierof commented on v6/ru/ViewManager.md
> +Ещё одна опция у настроек для `ShowExtendedInputDialog()` это `ExtendedInputSettings.EnableBarcode = true`, которая идёт совместно с `ExtendedInputSettings.TabTitleBarcode`. Фактически не нужен. Возм
Ок, можно не писать :)
Просто я хотела дать какую-то мотивацию, зачем у нас два совершенно одинаково функционирующие опции. И одна из них про штрихкоды.

Почему написала про баг – начала исследовать отличия Barcode-окна от NumericString-окна  и на интуитивном уровне казалось, что в Barcode-окне можно прокатать штрихкод. Возможно, у кого-то из разработчиков/клиентов будут такие же ожидания и можно было бы их предостеречь.

2018-11-30 14:32 UTC, ierof commented on v6/ru/ViewManager.md
> +Во-вторых, т.к. планиг это отдельный процесс, по умолчанию показанное из плагина окно не приобретает фокус. Фокус окну может дать только пользователь. Есть разные способы решить задачу форсированного
Тогда может вынесу эту информацию в отдельную статью или вообще в issue в этом проекте, и закроем её как fixed :) 

Попутный вопрос: issue тут заводить можно на русском или надо на английском? 
С одной стороны, портал международный. С другой – все потребители нашего api на данный момент, насколько мне известно, русскоязычные.

2018-11-30 15:04 UTC, ierof commented on v6/ru/ViewManager.md
> +Если вам нужно показать уведомительное сообщение пользователю, то рекомендуется использовать [`OperationService.AddNotificationMessage()`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Ap
Перечитала целиком предложение. Да, криво написано. Пока писала, отвлекалась и потеряла часть мысли.

2018-11-30 15:13 UTC, ierof commented on v6/ru/ViewManager.md
> +    TabTitleNumericString = "Ваш поясняющий текст числам"
текст поправлю, а картинки можно не буду переснимать? :)

2018-12-03 11:36 UTC, merged