RMS-50477 Поддержка режима «Табы»
iiko/front.api.doc pull request #54
Opened 2019-12-16 16:45 UTC by letolika

2019-12-16 18:13 UTC, vcpp requested changes

2019-12-16 18:13 UTC, vcpp commented on _posts/2019-12-17-mark-order-as-tab.md
> +Начиная с версии iikoRms 7.1.3 в режиме фастфуда появилась возможность помечать заказ как таб, дав ему особенное запоминающееся название. Более подробно о функционировании режима табов можно найти в
В общей ленте будет отображаться только первый абзац. В данном случае это нерелевантный текст.
Давай здесь напишем, что в V7 появится возможность отложить заказ в табы. А уж кто не знает, что такое табы, и кому это интересно, откроет новость и прочитает подробности в следующих абзацах.

2019-12-16 18:13 UTC, vcpp commented on _posts/2019-12-17-mark-order-as-tab.md
> +- [`ITerminalsGroup.IsTabMode`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_ITerminalsGroup_IsTabMode.htm). Включен ли режим табов для группы.
Как-то странно видеть точку между названием и описанием, но не критично. Я бы поставил тире :-)

2019-12-16 18:13 UTC, vcpp commented on _posts/2019-05-29-donations.md
> +С более подробной информацией можно ознакомиться в разделе [Чаевые и пожертвования]({{ site.baseurl }}/v6/ru/Donations.html)
Я бы ещё и слово «более» прочистил. Иногда оно просто избыточно, иногда может быть заменено прилагательным в сравнительной степени (более подробно = подробнее).

2019-12-17 07:49 UTC, letolika commented on _posts/2019-05-29-donations.md
> +С более подробной информацией можно ознакомиться в разделе [Чаевые и пожертвования]({{ site.baseurl }}/v6/ru/Donations.html)
+

2019-12-17 07:51 UTC, letolika commented on _posts/2019-12-17-mark-order-as-tab.md
> +- [`ITerminalsGroup.IsTabMode`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_ITerminalsGroup_IsTabMode.htm). Включен ли режим табов для группы.
done

2019-12-17 08:10 UTC, letolika commented on _posts/2019-12-17-mark-order-as-tab.md
> +Начиная с версии iikoRms 7.1.3 в режиме фастфуда появилась возможность помечать заказ как таб, дав ему особенное запоминающееся название. Более подробно о функционировании режима табов можно найти в
done

2019-12-17 09:14 UTC, merged