RMS-52778: документирвоание апи CheckPermission, CheckPermissions, ShowCheckPermissionPopup, ShowCheckPermissionsPopup
iiko/front.api.doc pull request #87
Opened 2021-08-13 11:45 UTC by zed220

Также были поправлены баги в предыдущей статье

2021-08-13 15:05 UTC, vcpp requested changes

2021-08-13 15:05 UTC, vcpp commented on v7/ru/CheckingPermissions.md
> +Действия, которые выполняются с помощью плагина, могут требовать проверки или запроса прав. Для проверки прав пользователя есть методы [`CheckPermission`](https://iiko.github.io/front.api.sdk/v7/html
На заметку (не требует исправления здесь и сейчас): git работает с текстом построчно, поэтому целый абзац одной строкой — не очень удобно с точки зрения возможных будущих правок, слияний изменений из разных веток, просмотра diff и т. п.

Поскольку одиночный перенос строки в md будет заменён на пробел, можно смело добавлять переносы. Я обычно вставляю переносы между предложениями, чтобы сохранить читабельность исходника. В случае длинных предложений можно добавить перенос где-нибудь между словами, по запятым и так далее. Главное не дойти до крайности и не начать писать в столбик по одному слову в строке :-)

2021-08-13 15:05 UTC, vcpp commented on v7/ru/CheckingPermissions.md
> +});
Если это единственное место, где меняется доступность кнопки, то можно сэкономить один или оба вызова в случаях, когда новое состояние совпадает с предыдущим или когда один и тот же пользователь заблокировал терминал и залогинился снова:

```cs
PluginContext.Notifications.CurrentUserChanged
    .Where(user => user != null)
    .DistinctUntilChanged()
    .Select(user => PluginContext.Operations.CheckPermission(user, "F_XR"))
    .DistinctUntilChanged()
    .Subscribe(isButtonEnabled => PluginContext.Operations.UpdatePaymentButtonState(subscription.buttonId, isEnabled: isButtonEnabled));
```

Не знаю, насколько стоит усложнять пример. С одной стороны, минималистичность примера использования хороша, никто не претендует на пригодность для промышленного использования. С другой стороны, многие могут просто не задумываться об оптимизациях, тупо копируя примеры...

Можно ещё добавить отслеживание `UserChanged` для текущего пользователя, чтобы на лету обновлять состояние кнопки по мере изменения набора его прав. Тоже усложнение, не знаю, нужное ли. Сам фронт всё на лету обновляет.

2021-08-13 15:05 UTC, vcpp commented on v7/ru/CheckingPermissions.md
> +- [`PermissionsCheckMode`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_PermissionsCheckMode.htm) `checkMode` - Проверять наличие всех прав (`PermissionsCheckMode.All`), или хотя бы
```suggestion
- [`PermissionsCheckMode`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_PermissionsCheckMode.htm) `checkMode` — проверять наличие всех прав (`PermissionsCheckMode.All`) или хотя бы одного (`PermissionsCheckMode.Any`).
```

Не буду настаивать писать со строчной или заглавной буквы после тире, лишь бы быть последовательным и везде одинаково поступать.

2021-08-13 15:05 UTC, vcpp commented on v7/ru/CheckingPermissions.md
> +В этом случае, окно запроса прав будет показываться всегда.
```suggestion
В этом случае окно запроса прав будет показываться всегда.
```

2021-08-13 15:05 UTC, vcpp commented on v7/ru/CheckingPermissions.md
> +Выполнение операции может требовать подтверждения права в любом случае, даже если текущий пользователь им уже обладает. Для этого, переделаем подписку нажатия на кнопку, передав в `showConfirmPopupAn
Тут можно привести пример, когда такой вариант имеет смысл — если операция потенциально опасная, необратимая, то требование прокатать карту становится дополнительным подтверждением намерения. А вдруг пользователь не хотел выполнять операцию, а случайно коснулся сенсорного экрана в зоне кнопки?

2021-08-13 15:05 UTC, vcpp commented on v7/ru/CheckingPermissions.md
> +#### Вариант 3.4: Запрашивать право в любом случае, даже если у пользователя оно есть. Подтвердить право может только текущий пользователь.
Странный вариант. Можешь предложить пример, когда это может понадобиться?
Я бы просто выше уточнил, что если окно показано, то прокатать можно карту любого сотрудника, не обязательно текущего пользователя. А дальше уж автор плагина с этой информацией сообразит, как дописать проверку, принадлежит ли карта текущему пользователю.

2021-08-13 15:05 UTC, vcpp commented on v7/ru/CheckingPermissions.md
> +        return;
Слушай, ну это уже не API, это логика в плагина, тут можно много чего напридумывать.
Я бы понял, если бы метод предлагал флажок а-ля `onlyCurrentUser` и окно проверки права не закрывалось при прокатке чужой карты. А тут просили право — подтвердили право, на этом апишная часть закончилась.

Ну и если уж отсутствующую в API логику имитировать в плагине, то после прокатки чужой карты нужно показать сообщение, что чужая карта не подходит, и затем повторно запрашивать право, иначе на UI это будет выглядеть странно — нажимаешь на кнопку, тебя просят подтвердить право, подтверждаешь, окно закрывается, операция не выполняется. По-хорошему, из окна проверки права должно быть два выхода — либо подтвердить право (в нашем случае именно картой текущего пользователя), либо нажать кнопку «Отмена». Прокатывая карту, пользователь выражает намерение выполнить операцию, и надо подсказать ему, что он делает неправильно и помочь сделать правильно. Если пользователь передумал выполнять операцию, он должен явно отменить её.

2021-08-13 15:05 UTC, vcpp commented on v7/ru/CheckingPermissions.md
> +### Вариант 3: Проверка нескольких прав.
Вариант 3 уже был.

2021-08-13 15:05 UTC, vcpp commented on v7/ru/CheckingPermissions.md
> +Метод возвращает экземпляр [`IUser`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Security_IUser.htm) - пользователь, который подтвердил права, либо *null*, если права не были
А почему `null` курсивом? По идее, надо моноширинным шрифтом показать, как и другие куски кода.

2021-08-13 15:05 UTC, vcpp commented on _posts/2021-08-11-add-methods-for-checking-permissions.md
> +Для удобства работы добавлены методы для взятия текущего пользователя [`GetCurrentUser`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetCurrentUser.htm) и текущей
```suggestion
Для удобства работы добавлены методы для получения текущего пользователя [`GetCurrentUser`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetCurrentUser.htm) и его роли [`GetStrictAccordanceToScheduleUserRole`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetStrictAccordanceToScheduleUserRole.htm).
```

2021-08-13 15:05 UTC, vcpp commented on v7/ru/CheckingPermissions.md
> +- `string[] permissionCodes` — права, которое будут проверяться у текущего пользователя.
```suggestion
- `string[] permissionCodes` — права, которые будут проверяться у текущего пользователя.
```

2021-08-13 15:05 UTC, vcpp commented on v7/ru/CheckingPermissions.md
> +- [`PermissionsCheckMode`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_PermissionsCheckMode.htm) `checkMode` - Проверять наличие всех прав (`PermissionsCheckMode.All`), или хотя бы
```suggestion
- [`PermissionsCheckMode`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_PermissionsCheckMode.htm) `checkMode` - проверять наличие всех прав (`PermissionsCheckMode.All`) или хотя бы одного (`PermissionsCheckMode.Any`).
```

2021-08-13 16:12 UTC, zed220 commented on v7/ru/CheckingPermissions.md
> +});
Добавил частично, чтобы не сильно усложнять.

2021-08-16 05:52 UTC, rgalk commented on v7/ru/CheckingPermissions.md
> +Для проверки прав пользователя есть методы [`CheckPermission`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_CheckPermission.htm) и [`CheckPermissions`](https://iik
```suggestion
Для проверки прав пользователя есть методы [`CheckPermission`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_CheckPermission.htm) и [`CheckPermissions`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_CheckPermissions.htm).
```

2021-08-16 08:29 UTC, rgalk requested changes

2021-08-16 08:29 UTC, rgalk commented on v7/ru/CheckingPermissions.md
> +ля запроса прав можно показать диалоговые окна с помощью методов [`ShowCheckPermissionPopup`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_UI_IViewManager_ShowCheckPermissionPopup.h
```suggestion
Для запроса прав можно показать диалоговые окна с помощью методов [`ShowCheckPermissionPopup`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_UI_IViewManager_ShowCheckPermissionPopup.htm) и [`ShowCheckPermissionsPopup`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_UI_IViewManager_ShowCheckPermissionsPopup.htm). 
```

2021-08-16 08:29 UTC, rgalk commented on v7/ru/CheckingPermissions.md
> +- `bool showConfirmPopupAnyway` — если false, то окно покажется только в том случае, если у текущего пользователя нет права. Если true, то окно покажется в любом случае, даже если пользователь облада
```suggestion
- `bool showConfirmPopupAnyway` — если false, то окно покажется только в случае отсутствия права у текущего пользователя. Если true, то окно покажется, даже если пользователь обладает нужным правом.
```

2021-08-16 08:29 UTC, rgalk commented on v7/ru/CheckingPermissions.md
> +Для проверки прав пользователя есть методы [`CheckPermission`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_CheckPermission.htm) и [`CheckPermissions`](https://iik
```suggestion
Для проверки прав пользователя есть методы [`CheckPermission`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_CheckPermission.htm) и [`CheckPermissions`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_CheckPermissions.htm).
```

2021-08-16 08:29 UTC, rgalk commented on v7/ru/CheckingPermissions.md
> +- `bool showConfirmPopupAnyway` — если false, то окно покажется только в том случае, если у текущего пользователя нет прав. Если true, то окно покажется в любом случае, даже если пользователь обладае
```suggestion
- `bool showConfirmPopupAnyway` — если false, то окно покажется только в случае отсутствия права у текущего пользователя. Если true, то окно покажется, даже если пользователь обладает нужным правом.
```

2021-08-16 08:29 UTC, rgalk commented on v7/ru/CheckingPermissions.md
> +    if(info.vm.ShowCheckPermissionPopup("F_XR", true) == null) //Право не было подтверждено
```suggestion
    if (info.vm.ShowCheckPermissionPopup("F_XR", true) == null) //Право не было подтверждено
```

2021-08-16 08:29 UTC, rgalk commented on v7/ru/CheckingPermissions.md
> +    if(info.vm.ShowCheckPermissionPopup("F_XR", false) == null) //Право не было подтверждено
```suggestion
    if (info.vm.ShowCheckPermissionPopup("F_XR", false) == null) //Право не было подтверждено
```

2021-08-16 08:29 UTC, rgalk commented on v7/ru/CheckingPermissions.md
> +        if(subscription == null) //Была ли ранее создана кнопка
```suggestion
        if (subscription == null) //Была ли ранее создана кнопка
```

2021-08-16 08:29 UTC, rgalk commented on v7/ru/CheckingPermissions.md
> +Метод возвращает экземпляр [`IUser`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Security_IUser.htm) - пользователь, который подтвердил права, либо `null`, если права не были
```suggestion
Метод возвращает экземпляр [`IUser`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Security_IUser.htm) — пользователь, который подтвердил права, либо `null`, если права не были подтверждены.
```

2021-08-16 08:29 UTC, rgalk commented on v7/ru/CheckingPermissions.md
> +- [`PermissionsCheckMode`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_PermissionsCheckMode.htm) `checkMode` - проверять наличие всех прав (`PermissionsCheckMode.All`), или хотя бы
```suggestion
- [`PermissionsCheckMode`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_PermissionsCheckMode.htm) `checkMode` — проверять наличие всех прав (`PermissionsCheckMode.All`), или хотя бы одного (`PermissionsCheckMode.Any`).
```

2021-08-16 08:29 UTC, rgalk commented on v7/ru/CheckingPermissions.md
> +- [`PermissionsCheckMode`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_PermissionsCheckMode.htm) `checkMode` - проверять наличие всех прав (`PermissionsCheckMode.All`), или хотя бы
```suggestion
- [`PermissionsCheckMode`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_PermissionsCheckMode.htm) `checkMode` — проверять наличие всех прав (`PermissionsCheckMode.All`), или хотя бы одного (`PermissionsCheckMode.Any`).
```

2021-08-16 09:03 UTC, rgalk approved these changes

2021-08-18 14:52 UTC, merged