RMS-52740 Добавить новость про отображение относительного количества …
iiko/front.api.doc pull request #88
Opened 2021-08-18 15:51 UTC by OlgaBelilovskaya

…модификаторов.

2021-08-18 20:22 UTC, zed220 commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +[`IRestaurant.DisplayRelativeNumberOfModifiers.htm`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_IRestaurant_DisplayRelativeNumberOfModifiers.htm) - как абсолютно
```suggestion
[`IRestaurant.DisplayRelativeNumberOfModifiers`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_IRestaurant_DisplayRelativeNumberOfModifiers.htm) - как абсолютное количество, как было ранее, или как разницу между абсолютным количеством модификатора и его количеством по умолчанию.
```

2021-08-18 21:56 UTC, zed220 commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +В API V7 для ресторана появилась возможность настроить, как отображать количество групповых модификаторов блюда
Это вкусовщина, но я бы немного переделал текст, например как-то так:

В API V7 для типа обслуживания "Ресторан" добавлено свойство IRestaurant.DisplayRelativeNumberOfModifiers, позволяющее настроить отображение групповых модификаторов блюда. Если оно выставлено в false (по умолчанию, старое поведение), то будет отображаться абсолютное количество, если же в true - то будет показываться разница между абсолютным количеством модификатора и его количеством по умолчанию.

Пусть у блюда есть модификатор Сметана, входящий в группу модификаторов, и для данного модификатора выполняется ряд условий:

- количество модификатора зависит от количества основного блюда;
- модификатор является бесплатным;
- у блюда количество модификатора по умолчанию равно 3.

В этом случае, если увеличить количество модификатора Сметана в заказе на 2, при IRestaurant.DisplayRelativeNumberOfModifiers равном true отобразится +2 Сметана, а при IRestaurant.DisplayRelativeNumberOfModifiers равном false отобразится абсолютное количество х5 Сметана. То же самое при уменьшении количества модификатора Сметана на 1 - при IRestaurant.DisplayRelativeNumberOfModifiers равном true отобразится - Сметана, а при IRestaurant.DisplayRelativeNumberOfModifiers равном false отобразится х2 Сметана.

Данная настройка влияет на показ модификаторов на экранах редактирования заказа, закрытого заказа, списка доставок, спска заказов, кухонном экране и в сервис-чеках.

2021-08-18 21:57 UTC, zed220 commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +- `bool hideIfDefaultAmount` — настроено ли для данного группового модификаторов "Скрывать, если количество по умолчанию",
```suggestion
- `bool hideIfDefaultAmount` — настроено ли для данного группового модификатора "Скрывать, если количество по умолчанию",
```

2021-08-18 21:58 UTC, zed220 requested changes
Есть немного ошибок в тексте.

2021-08-19 15:51 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +В API V7 для ресторана появилась возможность настроить, как отображать количество групповых модификаторов блюда
Я отредактировала, не ровно как ты предложил, но вроде компромиссно, посмотри плз.

2021-08-19 15:52 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +- `bool hideIfDefaultAmount` — настроено ли для данного группового модификаторов "Скрывать, если количество по умолчанию",
Исправила.

2021-08-19 15:52 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +[`IRestaurant.DisplayRelativeNumberOfModifiers.htm`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_IRestaurant_DisplayRelativeNumberOfModifiers.htm) - как абсолютно
Исправила.

2021-08-19 19:25 UTC, zed220 approved these changes

2021-08-20 06:38 UTC, rgalk requested changes

2021-08-20 06:38 UTC, rgalk commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +В API V7 для ресторана появилась возможность настроить, как отображать количество групповых модификаторов блюда.
```suggestion
В API V7 для ресторана появилась возможность настроить отображение количества групповых модификаторов блюда.
```

2021-08-20 06:38 UTC, rgalk commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +Также добавлен метод [`GetModifierAmountString()`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetModifierAmountString.htm), позволяющий получить количество модиф
```suggestion
Также добавлен метод [`GetModifierAmountString()`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetModifierAmountString.htm), позволяющий получить строку количества порций модификатора с учетом настройки `IRestaurant.DisplayRelativeNumberOfModifiers`.
```

2021-08-20 06:38 UTC, rgalk commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +
```suggestion
```

2021-08-20 06:38 UTC, rgalk commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +- `decimal modifierAmount` — количество модификатора,
Интересно, понятно ли, что когда мы говорим "Количество модификатора", то имеем ввиду количество порций модификатора?

2021-08-20 11:07 UTC, OlgaBelilovskaya commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +- `decimal modifierAmount` — количество модификатора,
да фиг знает, во фронте то добавляются порции, да. если писать слово порций то народ задумается мол а что такое порция.

2021-08-20 11:54 UTC, rgalk commented on _posts/2021-08-18-display-relative-number-of-modifiers.md
> +- `decimal modifierAmount` — количество модификатора,
Тогда, давай оставим так.

2021-08-20 14:56 UTC, rgalk approved these changes

2021-08-20 14:56 UTC, merged