RMS-47868 Документация api оплаты
iiko/front.api.doc pull request #9
Opened 2018-12-20 18:28 UTC by ierof

Написать документацию про возмождности оплатного контура в api

2018-12-21 07:09 UTC, vcpp requested changes
Не осилил до конца. Попробуй ещё разок перечитать, поправить терминологию и ошибки, которые сама заметишь.

2018-12-21 07:09 UTC, vcpp commented on v6/ru/ViewManager.md
> +- Взаимодействие с реализованным в плагине типом оплаты: процесс сбора данных, проведения и возврата оплаты (см. [`IExternalPaymentProcessor`](http://iiko.github.io/front.api.sdk/v6/html/Methods_T_Re
```suggestion
- Взаимодействие с реализованным в плагине типом оплаты: процесс сбора данных, проведения и возврата оплаты (см. [`IExternalPaymentProcessor`](http://iiko.github.io/front.api.sdk/v6/html/Methods_T_Resto_Front_Api_V6_IExternalPaymentProcessor.htm "IExternalPaymentProcessor")) *(см. статью про [Api внешних типов оплаты](PaymentProcessor.html "Внешние типы оплаты"))*
```

2018-12-21 07:09 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +title: Процессор оплаты
```suggestion
title: Внешние типы оплаты
```

2018-12-21 07:09 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +# Оплата плагинным типом оплаты
```suggestion
# Интеграция с внешними типами оплаты
```

2018-12-21 07:09 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +Реализовав интерфейс [`IExternalPaymentProcessor`](http://iiko.github.io/front.api.sdk/v6/html/T_Resto_Front_Api_V6_IExternalPaymentProcessor.htm) и зарегистрировав его соответствующим образом, в сис
Зарегистрировав кого *его* — интерфейс? Нет ведь, реализацию интерфейса.
«В системе появится система» — у нас вообще систематически систематизируются системные системы.
«Реализовав и зарегистрировав ..., появится система» ≈ «увидев и написав комментарий, появится ревью».
«Системы оплаты кастомной логикой ... оплаты» — понятно, что больше непонятно, чем понятно.

Давай попробуем переформулировать.

2018-12-21 07:09 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +Для плагинов, использующих этот функционал вводится [обязательное лицензирование](https://ru.iiko.help/articles/#!api-documentations/apistart).
```suggestion
Для плагинов, реализующих внешние типы оплаты, вводится [обязательное лицензирование](https://ru.iiko.help/articles/#!api-documentations/apistart).
```

А почему ссылка на официальный сайт? Там же нет ничего кроме ссылки на прейскурант. Может, со слов «обязательное лицензирование» логичнее дать ссылку на статью о лицензировании? А уже оттуда можно будет попасть на официальную страничку.

2018-12-21 07:09 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +## Регистрация внешней системы оплаты
```suggestion
## Регистрация внешней платёжной системы
```

2018-12-21 07:09 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +Плагин должен регистрировать тип оплаты с помощью [`IOperationService.RegisterPaymentSystem(...)`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_RegisterPaymentSy
Почему сразу «должен»? Кому должен? Давай нейтрально:
```suggestion
Плагин регистрирует платёжную систему с помощью [`IOperationService.RegisterPaymentSystem(...)`](http://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_IOperationService_RegisterPaymentSystem.htm)
```

2018-12-21 07:09 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +var disposable = PluginContext.Operations.RegisterPaymentSystem(paymentSystem);
Я бы выбросил этот однострочный пример. На предыдущей строчке мы сказали, какой метод нужно использовать, неужто без примера разработчик не осилит вызов этого метода?

2018-12-21 07:09 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +`paymentSystem` – экземпляр класса, реализующего `IExternalPaymentProcessor`.
Пример реально разрывает абзац, лишние переносы строк, продолжение предложения с заглавной буквы...
Давай склеим: «Плагин регистрирует платёжную систему с помощью метода xxx, передавая в него ..» и дальше про класс, реализующий интерфейс.

2018-12-21 07:09 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +В результате регистрации оплатного плагина в iikoOffice появится новая система оплаты в разделе «Внешний тип оплаты» с `IExternalPaymentProcessor.PaymentSystemName`.
«Реализовав интерфейс и зарегистрировав его»
«Регистрация системы оплаты»
«зарегистрировать тип оплаты»
«регистрации оплатного плагина»
Надо причесать терминологию, убрав зоопарк тех, кого мы регистрируем — интерфейс, реализацию, систему, тип оплаты или плагин.

2018-12-21 07:09 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +- *Система оплаты* – декларирует, как именно осуществлять проведение и возврат платежей. На всю систему iiko система оплаты декларируется в единственном экземпляре.
Уф, ну какая система оплаты. Попробуй набрать в гугле [система оплаты](https://www.google.com/?q=%22%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0+%D0%BE%D0%BF%D0%BB%D0%B0%D1%82%D1%8B%22), там 10 ссылок из 10 про системы оплаты труда и зарплаты. У нас платёжные системы.

2018-12-24 07:20 UTC, vcpp requested changes

2018-12-24 07:20 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +Для плагинов, реализующих внешние типы оплаты, вводится [обязательное лицензирование](Licensing.html).
Кстати, а ведь лицензирование нынче обязательно для любых плагинов :-(
```suggestion
Для плагинов, реализующих внешние типы оплаты, вводится [специальное лицензирование](Licensing.html).
```

2018-12-24 07:20 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +- Затем обратится к гостиничному сервису
```suggestion
- Затем обратиться к гостиничному сервису
```

2018-12-24 07:20 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +- Для последующей отмены понадобится знать, карта ли была прокатана или введен номер.
Надо списки причесать пунктуацию списков. Если уж ставить точки, то везде. Либо точку ставим в конце последнего пункта, а остальные строчки завершаем запятой, но тогда и начинать надо со строчной буквы.

2018-12-24 07:20 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +то это будет выглядеть так:
Так и задумано, что сначала идёт «если», затем шестистрочный список и только потом «то»? Как-то оно оторванно выглядит.

2018-12-24 07:20 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +	var cardInfoData = new IsCardClass { IsCard = card != null };
Если называть класс `IsCardClass`, изначально говоря, что он про единственное поле `IsCard`, то проще выбросить класс и дальше использовать непосредственно bool. Зачем нам обёртка над bool?

2018-12-24 07:20 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +Методы считаются успешно завершёнными, если в процессе выполнения не возникло исключений типа `PaymentActionFailedException` или `PaymentActionCancelledException`. Если это исключения возникли, так ж
Если эти..

2018-12-24 07:20 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +Метод возвращает `bool`, смысл возвращаемого значения следующий: доступно ли изменение суммы элемента предварительной оплаты с UI после совершения данного метода.
после *совершения* метода? Может, *завершения*?
А вообще плохо, что смысл bool'а неочевиден из названия метода, и его приходится подробно разъяснять в доке. Надо подумать о возврате dto'шки с полем (полями), что позволит дать «говорящие» имена.

2018-12-24 07:20 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +Некоторым внешним платёжным системам нужно выполнять на своей стороне необходимые действия при открытии и закрытии кассовой смены на iikoFront.
«нужно выполнять необходимые действия» — масло масленое. Я бы оставил «необходимо выполнять определённые действия при ...»

2018-12-24 07:20 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +Для этого нужно подписаться на [`INotificationService._SubscribeOnCafeSessionOpening`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_INotificationService_SubscribeOnCafeSessionOpe
```suggestion
Для этого нужно подписаться на [`INotificationService.SubscribeOnCafeSessionOpening`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_INotificationService_SubscribeOnCafeSessionOpening.htm) и [`INotificationService.SubscribeOnCafeSessionClosing`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_V6_INotificationService_SubscribeOnCafeSessionClosing.htm).
```

2018-12-24 07:20 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +	PluginContext.Log.Info("Cafe Session Opening.");
В лог можно писать обычный текст, без CamelCase :-)

2018-12-24 07:20 UTC, vcpp commented on v6/ru/PaymentProcessor.md
> +Исключения, возникшие в процессе выполнения `CafeSessionOpening()` и `CafeSessionClosing()`, не прерывают операций открытия и закрытия кассовой смены на iikoFront.
Не стоит ли уточнить, что обработчик, бросивший исключение, считается сломанным и больше вызываться не будет?

2018-12-24 10:36 UTC, ierof commented on v6/ru/PaymentProcessor.md
> +	var cardInfoData = new IsCardClass { IsCard = card != null };
Это пример использования. Чтобы не было ступора, как быть, если нужно что-то более сложное, чем bool

2018-12-24 10:42 UTC, ierof commented on v6/ru/PaymentProcessor.md
> +Метод возвращает `bool`, смысл возвращаемого значения следующий: доступно ли изменение суммы элемента предварительной оплаты с UI после совершения данного метода.
Да, смысл bool-а настолько неочевиден, что я пошла читать код. В доке эта штука прокомментирована на английском, добавлю ссылку.

2018-12-24 10:52 UTC, ierof commented on v6/ru/PaymentProcessor.md
> +Исключения, возникшие в процессе выполнения `CafeSessionOpening()` и `CafeSessionClosing()`, не прерывают операций открытия и закрытия кассовой смены на iikoFront.
Не знала, что больше вызываться не будет. Сейчас проверю.

2018-12-24 12:13 UTC, merged