RMS-52167
iiko/front.api.doc pull request #93
Opened 2021-10-20 13:31 UTC by letolica

2021-10-20 21:25 UTC, vcpp requested changes

2021-10-20 21:25 UTC, vcpp commented on _posts/2021-10-20-restaurant-properties.md
> +- [`Resto.Front.Api.Data.DataTransferObjects.LegalAddress LegalAddressDetailed`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_IRestaurant_LegalAddressDetailed.htm)
Как-то громоздко [выглядит](https://letolica.github.io/front.api.doc/2021/10/20/restaurant-properties.html).

Я бы тут указал тип `LegalAddress` без namespace. Во-первых, в современных IDE редко приходится руками писать using'и, достаточно помнить имя типа, а дальше среда разработки сама найдёт и допишет недостающий using. Во-вторых, есть же гиперссылка, кому надо — перейдёт по ссылке и увидит подробности.

2021-10-20 21:25 UTC, vcpp commented on _posts/2021-10-20-restaurant-properties.md
> +— КПП.
Не хватает расшифровки для КПП.
Для меня КПП — коробка переключения передач, контрольно-пропускной пункт или авиагоризонт :-)

Предлагаю расшифровать аббревиатуру и дать ссылку на википедию:
`string AccountingReasonCode` — [код причины постановки на учёт (КПП)](https://ru.wikipedia.org/wiki/%D0%98%D0%B4%D0%B5%D0%BD%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BD%D0%BE%D0%BC%D0%B5%D1%80_%D0%BD%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%89%D0%B8%D0%BA%D0%B0#%D0%9A%D0%BE%D0%B4_%D0%BF%D1%80%D0%B8%D1%87%D0%B8%D0%BD%D1%8B_%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B8_%D0%BD%D0%B0_%D1%83%D1%87%D1%91%D1%82_(%D0%9A%D0%9F%D0%9F))

2021-10-21 06:37 UTC, letolica commented on _posts/2021-10-20-restaurant-properties.md
> +- [`Resto.Front.Api.Data.DataTransferObjects.LegalAddress LegalAddressDetailed`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_IRestaurant_LegalAddressDetailed.htm)
Исправила.

2021-10-21 06:37 UTC, ghost commented on _posts/2021-10-20-restaurant-properties.md
> +— КПП.
Исправила.

2021-10-21 08:12 UTC, vcpp commented on _posts/2021-10-20-restaurant-properties.md
> +— КПП.
Без ссылки на wiki?
В принципе, по расшифровке «код причины постановки на учёт» несложно нагуглить, можно и без ссылки.

2021-10-21 08:12 UTC, merged

2021-10-21 08:16 UTC, letolica commented on _posts/2021-10-20-restaurant-properties.md
> +— КПП.
Это же просто название поля. В бэке оно называется КПП, а по факту туда можно записать что угодно.