RMS-50427 Front.Api: Дать возможность узнать, к какому отделению принадлежит стол
iiko/front.api.doc pull request #98
Opened 2021-11-02 08:00 UTC by nick-samygin

Публикация новости

2021-11-02 14:17 UTC, vcpp requested changes
Общее замечание по структуре файла: в общем списке изменений от каждой заметки показывается только первый абзац, поэтому важно, чтобы там был краткий обзор изменения. У тебя в первом абзаце описано лишь старое поведение, в таком виде changelog получится неправильный.

Посмотри [статью](https://wiki.iiko.ru/pages/viewpage.action?pageId=63407666).

2021-11-02 14:17 UTC, vcpp commented on _posts/2021-11-02-restaurant-section-added-to-table.md
> +title: В интерфейс ITable добавлена прямая ссылка на отделение, к которому принадлежит стол
Мне кажется, достаточно написать просто «ссылка». Смысл тот же.

2021-11-02 14:17 UTC, vcpp commented on _posts/2021-11-02-restaurant-section-added-to-table.md
> +Ранее для того что бы найти отделение ресторана, к которому принадлежит стол требовалось запросить все отделения через метод [`GetTerminalsGroupRestaurantSections`](https://iiko.github.io/front.api.s
```suggestion
Ранее для того что бы найти отделение ресторана, к которому принадлежит стол, требовалось запросить все отделения через метод [`GetTerminalsGroupRestaurantSections`](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_GetTerminalsGroupRestaurantSections.htm) и, перебирая столы в каждом отделении, найти искомое.
```

Пунктуация :-)

2021-11-02 14:17 UTC, vcpp commented on _posts/2021-11-02-restaurant-section-added-to-table.md
> +Теперь же, в интерфейс [`ITable`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Organization_Sections_ITable.htm) добавлено свойство [`RestaurantSection`](https://iiko.github.io
```suggestion
Теперь же в интерфейс [`ITable`](https://iiko.github.io/front.api.sdk/v7/html/T_Resto_Front_Api_Data_Organization_Sections_ITable.htm) добавлено свойство [`RestaurantSection`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_Data_Organization_Sections_ITable_RestaurantSection.htm), возвращающее ссылку на отделение ресторана.
```

Трудозатраты разработчика и дополнительные усилия — это одно и то же, про это можно не писать, и так очевидно.

2021-11-08 18:02 UTC, nick-samygin commented on _posts/2021-11-02-restaurant-section-added-to-table.md
> +title: В интерфейс ITable добавлена прямая ссылка на отделение, к которому принадлежит стол
Да, наверное, так будет лучше. Убрал.

2021-11-10 07:57 UTC, merged